/*
Asserts, Inc

Asserts Public API

API version: 2026.06.30-090528
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// PinnedFiltersConfigControllerAPIService PinnedFiltersConfigControllerAPI service
type PinnedFiltersConfigControllerAPIService service

type ApiGetPinnedFiltersConfigRequest struct {
	ctx         context.Context
	ApiService  *PinnedFiltersConfigControllerAPIService
	xScopeOrgID *string
}

// Grafana Tenant/Stack ID
func (r ApiGetPinnedFiltersConfigRequest) XScopeOrgID(xScopeOrgID string) ApiGetPinnedFiltersConfigRequest {
	r.xScopeOrgID = &xScopeOrgID
	return r
}

func (r ApiGetPinnedFiltersConfigRequest) Execute() (*PinnedFiltersConfig, *http.Response, error) {
	return r.ApiService.GetPinnedFiltersConfigExecute(r)
}

/*
GetPinnedFiltersConfig Method for GetPinnedFiltersConfig

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetPinnedFiltersConfigRequest
*/
func (a *PinnedFiltersConfigControllerAPIService) GetPinnedFiltersConfig(ctx context.Context) ApiGetPinnedFiltersConfigRequest {
	return ApiGetPinnedFiltersConfigRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return PinnedFiltersConfig
func (a *PinnedFiltersConfigControllerAPIService) GetPinnedFiltersConfigExecute(r ApiGetPinnedFiltersConfigRequest) (*PinnedFiltersConfig, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *PinnedFiltersConfig
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PinnedFiltersConfigControllerAPIService.GetPinnedFiltersConfig")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/config/display/pinned-filters"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xScopeOrgID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Scope-OrgID", r.xScopeOrgID, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPutPinnedFiltersConfigRequest struct {
	ctx                 context.Context
	ApiService          *PinnedFiltersConfigControllerAPIService
	xScopeOrgID         *string
	pinnedFiltersConfig *PinnedFiltersConfig
}

// Grafana Tenant/Stack ID
func (r ApiPutPinnedFiltersConfigRequest) XScopeOrgID(xScopeOrgID string) ApiPutPinnedFiltersConfigRequest {
	r.xScopeOrgID = &xScopeOrgID
	return r
}

func (r ApiPutPinnedFiltersConfigRequest) PinnedFiltersConfig(pinnedFiltersConfig PinnedFiltersConfig) ApiPutPinnedFiltersConfigRequest {
	r.pinnedFiltersConfig = &pinnedFiltersConfig
	return r
}

func (r ApiPutPinnedFiltersConfigRequest) Execute() (*http.Response, error) {
	return r.ApiService.PutPinnedFiltersConfigExecute(r)
}

/*
PutPinnedFiltersConfig Method for PutPinnedFiltersConfig

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiPutPinnedFiltersConfigRequest
*/
func (a *PinnedFiltersConfigControllerAPIService) PutPinnedFiltersConfig(ctx context.Context) ApiPutPinnedFiltersConfigRequest {
	return ApiPutPinnedFiltersConfigRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *PinnedFiltersConfigControllerAPIService) PutPinnedFiltersConfigExecute(r ApiPutPinnedFiltersConfigRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PinnedFiltersConfigControllerAPIService.PutPinnedFiltersConfig")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/config/display/pinned-filters"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xScopeOrgID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Scope-OrgID", r.xScopeOrgID, "")
	}
	// body params
	localVarPostBody = r.pinnedFiltersConfig
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
