/*
Asserts, Inc

Asserts Public API

API version: 2026.04.10-144303
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// CypherSearchControllerAPIService CypherSearchControllerAPI service
type CypherSearchControllerAPIService service

type ApiSearch1Request struct {
	ctx                    context.Context
	ApiService             *CypherSearchControllerAPIService
	cypherSearchRequestDto *CypherSearchRequestDto
	xScopeOrgID            *string
}

func (r ApiSearch1Request) CypherSearchRequestDto(cypherSearchRequestDto CypherSearchRequestDto) ApiSearch1Request {
	r.cypherSearchRequestDto = &cypherSearchRequestDto
	return r
}

// Grafana Tenant/Stack ID
func (r ApiSearch1Request) XScopeOrgID(xScopeOrgID string) ApiSearch1Request {
	r.xScopeOrgID = &xScopeOrgID
	return r
}

func (r ApiSearch1Request) Execute() (*CypherSearchResponseDto, *http.Response, error) {
	return r.ApiService.Search1Execute(r)
}

/*
Search1 Method for Search1

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSearch1Request
*/
func (a *CypherSearchControllerAPIService) Search1(ctx context.Context) ApiSearch1Request {
	return ApiSearch1Request{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CypherSearchResponseDto
func (a *CypherSearchControllerAPIService) Search1Execute(r ApiSearch1Request) (*CypherSearchResponseDto, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CypherSearchResponseDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CypherSearchControllerAPIService.Search1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/search/cypher"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.cypherSearchRequestDto == nil {
		return localVarReturnValue, nil, reportError("cypherSearchRequestDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/x-yml", "application/x-yaml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xScopeOrgID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Scope-OrgID", r.xScopeOrgID, "")
	}
	// body params
	localVarPostBody = r.cypherSearchRequestDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
