/*
Asserts, Inc

Asserts Public API

API version: 2026.04.09-111419
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the SearchCountRequestDtoTimeCriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCountRequestDtoTimeCriteria{}

// SearchCountRequestDtoTimeCriteria struct for SearchCountRequestDtoTimeCriteria
type SearchCountRequestDtoTimeCriteria struct {
	Start                int64 `json:"start"`
	End                  int64 `json:"end"`
	AdditionalProperties map[string]interface{}
}

type _SearchCountRequestDtoTimeCriteria SearchCountRequestDtoTimeCriteria

// NewSearchCountRequestDtoTimeCriteria instantiates a new SearchCountRequestDtoTimeCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCountRequestDtoTimeCriteria(start int64, end int64) *SearchCountRequestDtoTimeCriteria {
	this := SearchCountRequestDtoTimeCriteria{}
	this.Start = start
	this.End = end
	return &this
}

// NewSearchCountRequestDtoTimeCriteriaWithDefaults instantiates a new SearchCountRequestDtoTimeCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCountRequestDtoTimeCriteriaWithDefaults() *SearchCountRequestDtoTimeCriteria {
	this := SearchCountRequestDtoTimeCriteria{}
	return &this
}

// GetStart returns the Start field value
func (o *SearchCountRequestDtoTimeCriteria) GetStart() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *SearchCountRequestDtoTimeCriteria) GetStartOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *SearchCountRequestDtoTimeCriteria) SetStart(v int64) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *SearchCountRequestDtoTimeCriteria) GetEnd() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *SearchCountRequestDtoTimeCriteria) GetEndOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *SearchCountRequestDtoTimeCriteria) SetEnd(v int64) {
	o.End = v
}

func (o SearchCountRequestDtoTimeCriteria) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCountRequestDtoTimeCriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchCountRequestDtoTimeCriteria) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSearchCountRequestDtoTimeCriteria := _SearchCountRequestDtoTimeCriteria{}

	err = json.Unmarshal(data, &varSearchCountRequestDtoTimeCriteria)

	if err != nil {
		return err
	}

	*o = SearchCountRequestDtoTimeCriteria(varSearchCountRequestDtoTimeCriteria)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "start")
		delete(additionalProperties, "end")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchCountRequestDtoTimeCriteria struct {
	value *SearchCountRequestDtoTimeCriteria
	isSet bool
}

func (v NullableSearchCountRequestDtoTimeCriteria) Get() *SearchCountRequestDtoTimeCriteria {
	return v.value
}

func (v *NullableSearchCountRequestDtoTimeCriteria) Set(val *SearchCountRequestDtoTimeCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCountRequestDtoTimeCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCountRequestDtoTimeCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCountRequestDtoTimeCriteria(val *SearchCountRequestDtoTimeCriteria) *NullableSearchCountRequestDtoTimeCriteria {
	return &NullableSearchCountRequestDtoTimeCriteria{value: val, isSet: true}
}

func (v NullableSearchCountRequestDtoTimeCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCountRequestDtoTimeCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
