/*
Asserts, Inc

Asserts Public API

API version: 2026.09.23-074358
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the CypherQueryStatsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CypherQueryStatsDto{}

// CypherQueryStatsDto struct for CypherQueryStatsDto
type CypherQueryStatsDto struct {
	RowCount             *int32 `json:"rowCount,omitempty"`
	ColumnCount          *int32 `json:"columnCount,omitempty"`
	ElapsedMs            *int64 `json:"elapsedMs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CypherQueryStatsDto CypherQueryStatsDto

// NewCypherQueryStatsDto instantiates a new CypherQueryStatsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCypherQueryStatsDto() *CypherQueryStatsDto {
	this := CypherQueryStatsDto{}
	return &this
}

// NewCypherQueryStatsDtoWithDefaults instantiates a new CypherQueryStatsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCypherQueryStatsDtoWithDefaults() *CypherQueryStatsDto {
	this := CypherQueryStatsDto{}
	return &this
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *CypherQueryStatsDto) GetRowCount() int32 {
	if o == nil || IsNil(o.RowCount) {
		var ret int32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryStatsDto) GetRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *CypherQueryStatsDto) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given int32 and assigns it to the RowCount field.
func (o *CypherQueryStatsDto) SetRowCount(v int32) {
	o.RowCount = &v
}

// GetColumnCount returns the ColumnCount field value if set, zero value otherwise.
func (o *CypherQueryStatsDto) GetColumnCount() int32 {
	if o == nil || IsNil(o.ColumnCount) {
		var ret int32
		return ret
	}
	return *o.ColumnCount
}

// GetColumnCountOk returns a tuple with the ColumnCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryStatsDto) GetColumnCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ColumnCount) {
		return nil, false
	}
	return o.ColumnCount, true
}

// HasColumnCount returns a boolean if a field has been set.
func (o *CypherQueryStatsDto) HasColumnCount() bool {
	if o != nil && !IsNil(o.ColumnCount) {
		return true
	}

	return false
}

// SetColumnCount gets a reference to the given int32 and assigns it to the ColumnCount field.
func (o *CypherQueryStatsDto) SetColumnCount(v int32) {
	o.ColumnCount = &v
}

// GetElapsedMs returns the ElapsedMs field value if set, zero value otherwise.
func (o *CypherQueryStatsDto) GetElapsedMs() int64 {
	if o == nil || IsNil(o.ElapsedMs) {
		var ret int64
		return ret
	}
	return *o.ElapsedMs
}

// GetElapsedMsOk returns a tuple with the ElapsedMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryStatsDto) GetElapsedMsOk() (*int64, bool) {
	if o == nil || IsNil(o.ElapsedMs) {
		return nil, false
	}
	return o.ElapsedMs, true
}

// HasElapsedMs returns a boolean if a field has been set.
func (o *CypherQueryStatsDto) HasElapsedMs() bool {
	if o != nil && !IsNil(o.ElapsedMs) {
		return true
	}

	return false
}

// SetElapsedMs gets a reference to the given int64 and assigns it to the ElapsedMs field.
func (o *CypherQueryStatsDto) SetElapsedMs(v int64) {
	o.ElapsedMs = &v
}

func (o CypherQueryStatsDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CypherQueryStatsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RowCount) {
		toSerialize["rowCount"] = o.RowCount
	}
	if !IsNil(o.ColumnCount) {
		toSerialize["columnCount"] = o.ColumnCount
	}
	if !IsNil(o.ElapsedMs) {
		toSerialize["elapsedMs"] = o.ElapsedMs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CypherQueryStatsDto) UnmarshalJSON(data []byte) (err error) {
	varCypherQueryStatsDto := _CypherQueryStatsDto{}

	err = json.Unmarshal(data, &varCypherQueryStatsDto)

	if err != nil {
		return err
	}

	*o = CypherQueryStatsDto(varCypherQueryStatsDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rowCount")
		delete(additionalProperties, "columnCount")
		delete(additionalProperties, "elapsedMs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCypherQueryStatsDto struct {
	value *CypherQueryStatsDto
	isSet bool
}

func (v NullableCypherQueryStatsDto) Get() *CypherQueryStatsDto {
	return v.value
}

func (v *NullableCypherQueryStatsDto) Set(val *CypherQueryStatsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCypherQueryStatsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCypherQueryStatsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCypherQueryStatsDto(val *CypherQueryStatsDto) *NullableCypherQueryStatsDto {
	return &NullableCypherQueryStatsDto{value: val, isSet: true}
}

func (v NullableCypherQueryStatsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCypherQueryStatsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
