/*
Asserts, Inc

Asserts Public API

API version: 2026.02.11-155702
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the LlmRcaPatternDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LlmRcaPatternDto{}

// LlmRcaPatternDto struct for LlmRcaPatternDto
type LlmRcaPatternDto struct {
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LlmRcaPatternDto LlmRcaPatternDto

// NewLlmRcaPatternDto instantiates a new LlmRcaPatternDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLlmRcaPatternDto() *LlmRcaPatternDto {
	this := LlmRcaPatternDto{}
	return &this
}

// NewLlmRcaPatternDtoWithDefaults instantiates a new LlmRcaPatternDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLlmRcaPatternDtoWithDefaults() *LlmRcaPatternDto {
	this := LlmRcaPatternDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LlmRcaPatternDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LlmRcaPatternDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LlmRcaPatternDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LlmRcaPatternDto) SetName(v string) {
	o.Name = &v
}

func (o LlmRcaPatternDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LlmRcaPatternDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LlmRcaPatternDto) UnmarshalJSON(data []byte) (err error) {
	varLlmRcaPatternDto := _LlmRcaPatternDto{}

	err = json.Unmarshal(data, &varLlmRcaPatternDto)

	if err != nil {
		return err
	}

	*o = LlmRcaPatternDto(varLlmRcaPatternDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLlmRcaPatternDto struct {
	value *LlmRcaPatternDto
	isSet bool
}

func (v NullableLlmRcaPatternDto) Get() *LlmRcaPatternDto {
	return v.value
}

func (v *NullableLlmRcaPatternDto) Set(val *LlmRcaPatternDto) {
	v.value = val
	v.isSet = true
}

func (v NullableLlmRcaPatternDto) IsSet() bool {
	return v.isSet
}

func (v *NullableLlmRcaPatternDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLlmRcaPatternDto(val *LlmRcaPatternDto) *NullableLlmRcaPatternDto {
	return &NullableLlmRcaPatternDto{value: val, isSet: true}
}

func (v NullableLlmRcaPatternDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLlmRcaPatternDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
