/*
Asserts, Inc

Asserts Public API

API version: 2026.02.02-061707
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the ReorderConfigRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReorderConfigRequestDto{}

// ReorderConfigRequestDto Profile drilldown configuration data
type ReorderConfigRequestDto struct {
	OrderedConfigs       []ProfileConfigPriorityDto `json:"orderedConfigs"`
	AdditionalProperties map[string]interface{}
}

type _ReorderConfigRequestDto ReorderConfigRequestDto

// NewReorderConfigRequestDto instantiates a new ReorderConfigRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReorderConfigRequestDto(orderedConfigs []ProfileConfigPriorityDto) *ReorderConfigRequestDto {
	this := ReorderConfigRequestDto{}
	this.OrderedConfigs = orderedConfigs
	return &this
}

// NewReorderConfigRequestDtoWithDefaults instantiates a new ReorderConfigRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReorderConfigRequestDtoWithDefaults() *ReorderConfigRequestDto {
	this := ReorderConfigRequestDto{}
	return &this
}

// GetOrderedConfigs returns the OrderedConfigs field value
func (o *ReorderConfigRequestDto) GetOrderedConfigs() []ProfileConfigPriorityDto {
	if o == nil {
		var ret []ProfileConfigPriorityDto
		return ret
	}

	return o.OrderedConfigs
}

// GetOrderedConfigsOk returns a tuple with the OrderedConfigs field value
// and a boolean to check if the value has been set.
func (o *ReorderConfigRequestDto) GetOrderedConfigsOk() ([]ProfileConfigPriorityDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderedConfigs, true
}

// SetOrderedConfigs sets field value
func (o *ReorderConfigRequestDto) SetOrderedConfigs(v []ProfileConfigPriorityDto) {
	o.OrderedConfigs = v
}

func (o ReorderConfigRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReorderConfigRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orderedConfigs"] = o.OrderedConfigs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReorderConfigRequestDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varReorderConfigRequestDto := _ReorderConfigRequestDto{}

	err = json.Unmarshal(data, &varReorderConfigRequestDto)

	if err != nil {
		return err
	}

	*o = ReorderConfigRequestDto(varReorderConfigRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "orderedConfigs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReorderConfigRequestDto struct {
	value *ReorderConfigRequestDto
	isSet bool
}

func (v NullableReorderConfigRequestDto) Get() *ReorderConfigRequestDto {
	return v.value
}

func (v *NullableReorderConfigRequestDto) Set(val *ReorderConfigRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableReorderConfigRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableReorderConfigRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReorderConfigRequestDto(val *ReorderConfigRequestDto) *NullableReorderConfigRequestDto {
	return &NullableReorderConfigRequestDto{value: val, isSet: true}
}

func (v NullableReorderConfigRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReorderConfigRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
