/*
Asserts, Inc

Asserts Public API

API version: 2026.08.24-122123
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the AssertionSourceMetricResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertionSourceMetricResponseDto{}

// AssertionSourceMetricResponseDto struct for AssertionSourceMetricResponseDto
type AssertionSourceMetricResponseDto struct {
	MetricName           *string                         `json:"metricName,omitempty"`
	Labels               []AssertionSourceMetricLabelDto `json:"labels,omitempty"`
	MetricType           *string                         `json:"metricType,omitempty"`
	CustomRateInterval   *string                         `json:"customRateInterval,omitempty"`
	CustomFunction       *string                         `json:"customFunction,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AssertionSourceMetricResponseDto AssertionSourceMetricResponseDto

// NewAssertionSourceMetricResponseDto instantiates a new AssertionSourceMetricResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertionSourceMetricResponseDto() *AssertionSourceMetricResponseDto {
	this := AssertionSourceMetricResponseDto{}
	return &this
}

// NewAssertionSourceMetricResponseDtoWithDefaults instantiates a new AssertionSourceMetricResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertionSourceMetricResponseDtoWithDefaults() *AssertionSourceMetricResponseDto {
	this := AssertionSourceMetricResponseDto{}
	return &this
}

// GetMetricName returns the MetricName field value if set, zero value otherwise.
func (o *AssertionSourceMetricResponseDto) GetMetricName() string {
	if o == nil || IsNil(o.MetricName) {
		var ret string
		return ret
	}
	return *o.MetricName
}

// GetMetricNameOk returns a tuple with the MetricName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricResponseDto) GetMetricNameOk() (*string, bool) {
	if o == nil || IsNil(o.MetricName) {
		return nil, false
	}
	return o.MetricName, true
}

// HasMetricName returns a boolean if a field has been set.
func (o *AssertionSourceMetricResponseDto) HasMetricName() bool {
	if o != nil && !IsNil(o.MetricName) {
		return true
	}

	return false
}

// SetMetricName gets a reference to the given string and assigns it to the MetricName field.
func (o *AssertionSourceMetricResponseDto) SetMetricName(v string) {
	o.MetricName = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AssertionSourceMetricResponseDto) GetLabels() []AssertionSourceMetricLabelDto {
	if o == nil || IsNil(o.Labels) {
		var ret []AssertionSourceMetricLabelDto
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricResponseDto) GetLabelsOk() ([]AssertionSourceMetricLabelDto, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AssertionSourceMetricResponseDto) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []AssertionSourceMetricLabelDto and assigns it to the Labels field.
func (o *AssertionSourceMetricResponseDto) SetLabels(v []AssertionSourceMetricLabelDto) {
	o.Labels = v
}

// GetMetricType returns the MetricType field value if set, zero value otherwise.
func (o *AssertionSourceMetricResponseDto) GetMetricType() string {
	if o == nil || IsNil(o.MetricType) {
		var ret string
		return ret
	}
	return *o.MetricType
}

// GetMetricTypeOk returns a tuple with the MetricType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricResponseDto) GetMetricTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MetricType) {
		return nil, false
	}
	return o.MetricType, true
}

// HasMetricType returns a boolean if a field has been set.
func (o *AssertionSourceMetricResponseDto) HasMetricType() bool {
	if o != nil && !IsNil(o.MetricType) {
		return true
	}

	return false
}

// SetMetricType gets a reference to the given string and assigns it to the MetricType field.
func (o *AssertionSourceMetricResponseDto) SetMetricType(v string) {
	o.MetricType = &v
}

// GetCustomRateInterval returns the CustomRateInterval field value if set, zero value otherwise.
func (o *AssertionSourceMetricResponseDto) GetCustomRateInterval() string {
	if o == nil || IsNil(o.CustomRateInterval) {
		var ret string
		return ret
	}
	return *o.CustomRateInterval
}

// GetCustomRateIntervalOk returns a tuple with the CustomRateInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricResponseDto) GetCustomRateIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.CustomRateInterval) {
		return nil, false
	}
	return o.CustomRateInterval, true
}

// HasCustomRateInterval returns a boolean if a field has been set.
func (o *AssertionSourceMetricResponseDto) HasCustomRateInterval() bool {
	if o != nil && !IsNil(o.CustomRateInterval) {
		return true
	}

	return false
}

// SetCustomRateInterval gets a reference to the given string and assigns it to the CustomRateInterval field.
func (o *AssertionSourceMetricResponseDto) SetCustomRateInterval(v string) {
	o.CustomRateInterval = &v
}

// GetCustomFunction returns the CustomFunction field value if set, zero value otherwise.
func (o *AssertionSourceMetricResponseDto) GetCustomFunction() string {
	if o == nil || IsNil(o.CustomFunction) {
		var ret string
		return ret
	}
	return *o.CustomFunction
}

// GetCustomFunctionOk returns a tuple with the CustomFunction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricResponseDto) GetCustomFunctionOk() (*string, bool) {
	if o == nil || IsNil(o.CustomFunction) {
		return nil, false
	}
	return o.CustomFunction, true
}

// HasCustomFunction returns a boolean if a field has been set.
func (o *AssertionSourceMetricResponseDto) HasCustomFunction() bool {
	if o != nil && !IsNil(o.CustomFunction) {
		return true
	}

	return false
}

// SetCustomFunction gets a reference to the given string and assigns it to the CustomFunction field.
func (o *AssertionSourceMetricResponseDto) SetCustomFunction(v string) {
	o.CustomFunction = &v
}

func (o AssertionSourceMetricResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertionSourceMetricResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetricName) {
		toSerialize["metricName"] = o.MetricName
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.MetricType) {
		toSerialize["metricType"] = o.MetricType
	}
	if !IsNil(o.CustomRateInterval) {
		toSerialize["customRateInterval"] = o.CustomRateInterval
	}
	if !IsNil(o.CustomFunction) {
		toSerialize["customFunction"] = o.CustomFunction
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssertionSourceMetricResponseDto) UnmarshalJSON(data []byte) (err error) {
	varAssertionSourceMetricResponseDto := _AssertionSourceMetricResponseDto{}

	err = json.Unmarshal(data, &varAssertionSourceMetricResponseDto)

	if err != nil {
		return err
	}

	*o = AssertionSourceMetricResponseDto(varAssertionSourceMetricResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "metricName")
		delete(additionalProperties, "labels")
		delete(additionalProperties, "metricType")
		delete(additionalProperties, "customRateInterval")
		delete(additionalProperties, "customFunction")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssertionSourceMetricResponseDto struct {
	value *AssertionSourceMetricResponseDto
	isSet bool
}

func (v NullableAssertionSourceMetricResponseDto) Get() *AssertionSourceMetricResponseDto {
	return v.value
}

func (v *NullableAssertionSourceMetricResponseDto) Set(val *AssertionSourceMetricResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertionSourceMetricResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertionSourceMetricResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertionSourceMetricResponseDto(val *AssertionSourceMetricResponseDto) *NullableAssertionSourceMetricResponseDto {
	return &NullableAssertionSourceMetricResponseDto{value: val, isSet: true}
}

func (v NullableAssertionSourceMetricResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertionSourceMetricResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
