/*
Asserts, Inc

Asserts Public API

API version: 2026.03.27-112916
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the EntityScopesV2ResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityScopesV2ResponseDto{}

// EntityScopesV2ResponseDto struct for EntityScopesV2ResponseDto
type EntityScopesV2ResponseDto struct {
	ScopeValues          map[string][]ScopeValueDto `json:"scopeValues,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EntityScopesV2ResponseDto EntityScopesV2ResponseDto

// NewEntityScopesV2ResponseDto instantiates a new EntityScopesV2ResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityScopesV2ResponseDto() *EntityScopesV2ResponseDto {
	this := EntityScopesV2ResponseDto{}
	return &this
}

// NewEntityScopesV2ResponseDtoWithDefaults instantiates a new EntityScopesV2ResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityScopesV2ResponseDtoWithDefaults() *EntityScopesV2ResponseDto {
	this := EntityScopesV2ResponseDto{}
	return &this
}

// GetScopeValues returns the ScopeValues field value if set, zero value otherwise.
func (o *EntityScopesV2ResponseDto) GetScopeValues() map[string][]ScopeValueDto {
	if o == nil || IsNil(o.ScopeValues) {
		var ret map[string][]ScopeValueDto
		return ret
	}
	return o.ScopeValues
}

// GetScopeValuesOk returns a tuple with the ScopeValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityScopesV2ResponseDto) GetScopeValuesOk() (map[string][]ScopeValueDto, bool) {
	if o == nil || IsNil(o.ScopeValues) {
		return map[string][]ScopeValueDto{}, false
	}
	return o.ScopeValues, true
}

// HasScopeValues returns a boolean if a field has been set.
func (o *EntityScopesV2ResponseDto) HasScopeValues() bool {
	if o != nil && !IsNil(o.ScopeValues) {
		return true
	}

	return false
}

// SetScopeValues gets a reference to the given map[string][]ScopeValueDto and assigns it to the ScopeValues field.
func (o *EntityScopesV2ResponseDto) SetScopeValues(v map[string][]ScopeValueDto) {
	o.ScopeValues = v
}

func (o EntityScopesV2ResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityScopesV2ResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScopeValues) {
		toSerialize["scopeValues"] = o.ScopeValues
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EntityScopesV2ResponseDto) UnmarshalJSON(data []byte) (err error) {
	varEntityScopesV2ResponseDto := _EntityScopesV2ResponseDto{}

	err = json.Unmarshal(data, &varEntityScopesV2ResponseDto)

	if err != nil {
		return err
	}

	*o = EntityScopesV2ResponseDto(varEntityScopesV2ResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "scopeValues")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntityScopesV2ResponseDto struct {
	value *EntityScopesV2ResponseDto
	isSet bool
}

func (v NullableEntityScopesV2ResponseDto) Get() *EntityScopesV2ResponseDto {
	return v.value
}

func (v *NullableEntityScopesV2ResponseDto) Set(val *EntityScopesV2ResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityScopesV2ResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityScopesV2ResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityScopesV2ResponseDto(val *EntityScopesV2ResponseDto) *NullableEntityScopesV2ResponseDto {
	return &NullableEntityScopesV2ResponseDto{value: val, isSet: true}
}

func (v NullableEntityScopesV2ResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityScopesV2ResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
