/*
Asserts, Inc

Asserts Public API

API version: 2026.04.10-122016
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the SearchCountRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchCountRequestDto{}

// SearchCountRequestDto struct for SearchCountRequestDto
type SearchCountRequestDto struct {
	Items                []SearchCountRequestEntryDto        `json:"items"`
	TimeCriteria         SearchCountRequestDtoTimeCriteria   `json:"timeCriteria"`
	ScopeCriteria        *SearchCountRequestDtoScopeCriteria `json:"scopeCriteria,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchCountRequestDto SearchCountRequestDto

// NewSearchCountRequestDto instantiates a new SearchCountRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchCountRequestDto(items []SearchCountRequestEntryDto, timeCriteria SearchCountRequestDtoTimeCriteria) *SearchCountRequestDto {
	this := SearchCountRequestDto{}
	this.Items = items
	this.TimeCriteria = timeCriteria
	return &this
}

// NewSearchCountRequestDtoWithDefaults instantiates a new SearchCountRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchCountRequestDtoWithDefaults() *SearchCountRequestDto {
	this := SearchCountRequestDto{}
	return &this
}

// GetItems returns the Items field value
func (o *SearchCountRequestDto) GetItems() []SearchCountRequestEntryDto {
	if o == nil {
		var ret []SearchCountRequestEntryDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SearchCountRequestDto) GetItemsOk() ([]SearchCountRequestEntryDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SearchCountRequestDto) SetItems(v []SearchCountRequestEntryDto) {
	o.Items = v
}

// GetTimeCriteria returns the TimeCriteria field value
func (o *SearchCountRequestDto) GetTimeCriteria() SearchCountRequestDtoTimeCriteria {
	if o == nil {
		var ret SearchCountRequestDtoTimeCriteria
		return ret
	}

	return o.TimeCriteria
}

// GetTimeCriteriaOk returns a tuple with the TimeCriteria field value
// and a boolean to check if the value has been set.
func (o *SearchCountRequestDto) GetTimeCriteriaOk() (*SearchCountRequestDtoTimeCriteria, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeCriteria, true
}

// SetTimeCriteria sets field value
func (o *SearchCountRequestDto) SetTimeCriteria(v SearchCountRequestDtoTimeCriteria) {
	o.TimeCriteria = v
}

// GetScopeCriteria returns the ScopeCriteria field value if set, zero value otherwise.
func (o *SearchCountRequestDto) GetScopeCriteria() SearchCountRequestDtoScopeCriteria {
	if o == nil || IsNil(o.ScopeCriteria) {
		var ret SearchCountRequestDtoScopeCriteria
		return ret
	}
	return *o.ScopeCriteria
}

// GetScopeCriteriaOk returns a tuple with the ScopeCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchCountRequestDto) GetScopeCriteriaOk() (*SearchCountRequestDtoScopeCriteria, bool) {
	if o == nil || IsNil(o.ScopeCriteria) {
		return nil, false
	}
	return o.ScopeCriteria, true
}

// HasScopeCriteria returns a boolean if a field has been set.
func (o *SearchCountRequestDto) HasScopeCriteria() bool {
	if o != nil && !IsNil(o.ScopeCriteria) {
		return true
	}

	return false
}

// SetScopeCriteria gets a reference to the given SearchCountRequestDtoScopeCriteria and assigns it to the ScopeCriteria field.
func (o *SearchCountRequestDto) SetScopeCriteria(v SearchCountRequestDtoScopeCriteria) {
	o.ScopeCriteria = &v
}

func (o SearchCountRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchCountRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["timeCriteria"] = o.TimeCriteria
	if !IsNil(o.ScopeCriteria) {
		toSerialize["scopeCriteria"] = o.ScopeCriteria
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchCountRequestDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSearchCountRequestDto := _SearchCountRequestDto{}

	err = json.Unmarshal(data, &varSearchCountRequestDto)

	if err != nil {
		return err
	}

	*o = SearchCountRequestDto(varSearchCountRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "timeCriteria")
		delete(additionalProperties, "scopeCriteria")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchCountRequestDto struct {
	value *SearchCountRequestDto
	isSet bool
}

func (v NullableSearchCountRequestDto) Get() *SearchCountRequestDto {
	return v.value
}

func (v *NullableSearchCountRequestDto) Set(val *SearchCountRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchCountRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchCountRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchCountRequestDto(val *SearchCountRequestDto) *NullableSearchCountRequestDto {
	return &NullableSearchCountRequestDto{value: val, isSet: true}
}

func (v NullableSearchCountRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchCountRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
