/*
Asserts, Inc

Asserts Public API

API version: 2026.09.23-074358
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the CypherQueryRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CypherQueryRequestDto{}

// CypherQueryRequestDto struct for CypherQueryRequestDto
type CypherQueryRequestDto struct {
	Query                string                 `json:"query"`
	Start                *int64                 `json:"start,omitempty"`
	End                  *int64                 `json:"end,omitempty"`
	Parameters           map[string]interface{} `json:"parameters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CypherQueryRequestDto CypherQueryRequestDto

// NewCypherQueryRequestDto instantiates a new CypherQueryRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCypherQueryRequestDto(query string) *CypherQueryRequestDto {
	this := CypherQueryRequestDto{}
	this.Query = query
	return &this
}

// NewCypherQueryRequestDtoWithDefaults instantiates a new CypherQueryRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCypherQueryRequestDtoWithDefaults() *CypherQueryRequestDto {
	this := CypherQueryRequestDto{}
	return &this
}

// GetQuery returns the Query field value
func (o *CypherQueryRequestDto) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *CypherQueryRequestDto) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *CypherQueryRequestDto) SetQuery(v string) {
	o.Query = v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *CypherQueryRequestDto) GetStart() int64 {
	if o == nil || IsNil(o.Start) {
		var ret int64
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryRequestDto) GetStartOk() (*int64, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *CypherQueryRequestDto) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given int64 and assigns it to the Start field.
func (o *CypherQueryRequestDto) SetStart(v int64) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *CypherQueryRequestDto) GetEnd() int64 {
	if o == nil || IsNil(o.End) {
		var ret int64
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryRequestDto) GetEndOk() (*int64, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *CypherQueryRequestDto) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int64 and assigns it to the End field.
func (o *CypherQueryRequestDto) SetEnd(v int64) {
	o.End = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *CypherQueryRequestDto) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryRequestDto) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *CypherQueryRequestDto) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *CypherQueryRequestDto) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

func (o CypherQueryRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CypherQueryRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CypherQueryRequestDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varCypherQueryRequestDto := _CypherQueryRequestDto{}

	err = json.Unmarshal(data, &varCypherQueryRequestDto)

	if err != nil {
		return err
	}

	*o = CypherQueryRequestDto(varCypherQueryRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "query")
		delete(additionalProperties, "start")
		delete(additionalProperties, "end")
		delete(additionalProperties, "parameters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCypherQueryRequestDto struct {
	value *CypherQueryRequestDto
	isSet bool
}

func (v NullableCypherQueryRequestDto) Get() *CypherQueryRequestDto {
	return v.value
}

func (v *NullableCypherQueryRequestDto) Set(val *CypherQueryRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCypherQueryRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCypherQueryRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCypherQueryRequestDto(val *CypherQueryRequestDto) *NullableCypherQueryRequestDto {
	return &NullableCypherQueryRequestDto{value: val, isSet: true}
}

func (v NullableCypherQueryRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCypherQueryRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
