/*
Asserts, Inc

Asserts Public API

API version: 2026.03.27-112916
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the DrilldownConfigMigrationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DrilldownConfigMigrationDto{}

// DrilldownConfigMigrationDto struct for DrilldownConfigMigrationDto
type DrilldownConfigMigrationDto struct {
	DryRun                 *bool `json:"dryRun,omitempty"`
	RecreateDefaultConfigs *bool `json:"recreateDefaultConfigs,omitempty"`
	RecreateOtelLogConfig  *bool `json:"recreateOtelLogConfig,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _DrilldownConfigMigrationDto DrilldownConfigMigrationDto

// NewDrilldownConfigMigrationDto instantiates a new DrilldownConfigMigrationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDrilldownConfigMigrationDto() *DrilldownConfigMigrationDto {
	this := DrilldownConfigMigrationDto{}
	return &this
}

// NewDrilldownConfigMigrationDtoWithDefaults instantiates a new DrilldownConfigMigrationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDrilldownConfigMigrationDtoWithDefaults() *DrilldownConfigMigrationDto {
	this := DrilldownConfigMigrationDto{}
	return &this
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *DrilldownConfigMigrationDto) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrilldownConfigMigrationDto) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *DrilldownConfigMigrationDto) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *DrilldownConfigMigrationDto) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetRecreateDefaultConfigs returns the RecreateDefaultConfigs field value if set, zero value otherwise.
func (o *DrilldownConfigMigrationDto) GetRecreateDefaultConfigs() bool {
	if o == nil || IsNil(o.RecreateDefaultConfigs) {
		var ret bool
		return ret
	}
	return *o.RecreateDefaultConfigs
}

// GetRecreateDefaultConfigsOk returns a tuple with the RecreateDefaultConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrilldownConfigMigrationDto) GetRecreateDefaultConfigsOk() (*bool, bool) {
	if o == nil || IsNil(o.RecreateDefaultConfigs) {
		return nil, false
	}
	return o.RecreateDefaultConfigs, true
}

// HasRecreateDefaultConfigs returns a boolean if a field has been set.
func (o *DrilldownConfigMigrationDto) HasRecreateDefaultConfigs() bool {
	if o != nil && !IsNil(o.RecreateDefaultConfigs) {
		return true
	}

	return false
}

// SetRecreateDefaultConfigs gets a reference to the given bool and assigns it to the RecreateDefaultConfigs field.
func (o *DrilldownConfigMigrationDto) SetRecreateDefaultConfigs(v bool) {
	o.RecreateDefaultConfigs = &v
}

// GetRecreateOtelLogConfig returns the RecreateOtelLogConfig field value if set, zero value otherwise.
func (o *DrilldownConfigMigrationDto) GetRecreateOtelLogConfig() bool {
	if o == nil || IsNil(o.RecreateOtelLogConfig) {
		var ret bool
		return ret
	}
	return *o.RecreateOtelLogConfig
}

// GetRecreateOtelLogConfigOk returns a tuple with the RecreateOtelLogConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrilldownConfigMigrationDto) GetRecreateOtelLogConfigOk() (*bool, bool) {
	if o == nil || IsNil(o.RecreateOtelLogConfig) {
		return nil, false
	}
	return o.RecreateOtelLogConfig, true
}

// HasRecreateOtelLogConfig returns a boolean if a field has been set.
func (o *DrilldownConfigMigrationDto) HasRecreateOtelLogConfig() bool {
	if o != nil && !IsNil(o.RecreateOtelLogConfig) {
		return true
	}

	return false
}

// SetRecreateOtelLogConfig gets a reference to the given bool and assigns it to the RecreateOtelLogConfig field.
func (o *DrilldownConfigMigrationDto) SetRecreateOtelLogConfig(v bool) {
	o.RecreateOtelLogConfig = &v
}

func (o DrilldownConfigMigrationDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DrilldownConfigMigrationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}
	if !IsNil(o.RecreateDefaultConfigs) {
		toSerialize["recreateDefaultConfigs"] = o.RecreateDefaultConfigs
	}
	if !IsNil(o.RecreateOtelLogConfig) {
		toSerialize["recreateOtelLogConfig"] = o.RecreateOtelLogConfig
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DrilldownConfigMigrationDto) UnmarshalJSON(data []byte) (err error) {
	varDrilldownConfigMigrationDto := _DrilldownConfigMigrationDto{}

	err = json.Unmarshal(data, &varDrilldownConfigMigrationDto)

	if err != nil {
		return err
	}

	*o = DrilldownConfigMigrationDto(varDrilldownConfigMigrationDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dryRun")
		delete(additionalProperties, "recreateDefaultConfigs")
		delete(additionalProperties, "recreateOtelLogConfig")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDrilldownConfigMigrationDto struct {
	value *DrilldownConfigMigrationDto
	isSet bool
}

func (v NullableDrilldownConfigMigrationDto) Get() *DrilldownConfigMigrationDto {
	return v.value
}

func (v *NullableDrilldownConfigMigrationDto) Set(val *DrilldownConfigMigrationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDrilldownConfigMigrationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDrilldownConfigMigrationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDrilldownConfigMigrationDto(val *DrilldownConfigMigrationDto) *NullableDrilldownConfigMigrationDto {
	return &NullableDrilldownConfigMigrationDto{value: val, isSet: true}
}

func (v NullableDrilldownConfigMigrationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDrilldownConfigMigrationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
