/*
Asserts, Inc

Asserts Public API

API version: 2026.06.22-121348
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the StaticEnrichmentDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StaticEnrichmentDto{}

// StaticEnrichmentDto Literal enrichment record contributed by 'enrichedStatically'. Patches an existing entity but does not create or keep it alive.
type StaticEnrichmentDto struct {
	// Literal value used to match the target entity's name property
	Name string `json:"name"`
	// Literal scope label values used to match the target entity
	Scope map[string]string `json:"scope,omitempty"`
	// Literal property keys and values to patch onto the target entity
	Properties           map[string]string `json:"properties,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StaticEnrichmentDto StaticEnrichmentDto

// NewStaticEnrichmentDto instantiates a new StaticEnrichmentDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticEnrichmentDto(name string) *StaticEnrichmentDto {
	this := StaticEnrichmentDto{}
	this.Name = name
	return &this
}

// NewStaticEnrichmentDtoWithDefaults instantiates a new StaticEnrichmentDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticEnrichmentDtoWithDefaults() *StaticEnrichmentDto {
	this := StaticEnrichmentDto{}
	var name string = ""
	this.Name = name
	return &this
}

// GetName returns the Name field value
func (o *StaticEnrichmentDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StaticEnrichmentDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StaticEnrichmentDto) SetName(v string) {
	o.Name = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *StaticEnrichmentDto) GetScope() map[string]string {
	if o == nil || IsNil(o.Scope) {
		var ret map[string]string
		return ret
	}
	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticEnrichmentDto) GetScopeOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Scope) {
		return map[string]string{}, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *StaticEnrichmentDto) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given map[string]string and assigns it to the Scope field.
func (o *StaticEnrichmentDto) SetScope(v map[string]string) {
	o.Scope = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *StaticEnrichmentDto) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticEnrichmentDto) GetPropertiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]string{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *StaticEnrichmentDto) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *StaticEnrichmentDto) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o StaticEnrichmentDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StaticEnrichmentDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StaticEnrichmentDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varStaticEnrichmentDto := _StaticEnrichmentDto{}

	err = json.Unmarshal(data, &varStaticEnrichmentDto)

	if err != nil {
		return err
	}

	*o = StaticEnrichmentDto(varStaticEnrichmentDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStaticEnrichmentDto struct {
	value *StaticEnrichmentDto
	isSet bool
}

func (v NullableStaticEnrichmentDto) Get() *StaticEnrichmentDto {
	return v.value
}

func (v *NullableStaticEnrichmentDto) Set(val *StaticEnrichmentDto) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticEnrichmentDto) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticEnrichmentDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticEnrichmentDto(val *StaticEnrichmentDto) *NullableStaticEnrichmentDto {
	return &NullableStaticEnrichmentDto{value: val, isSet: true}
}

func (v NullableStaticEnrichmentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticEnrichmentDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
