/*
Asserts, Inc

Asserts Public API

API version: 2026.09.23-074358
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the CypherQueryResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CypherQueryResponseDto{}

// CypherQueryResponseDto struct for CypherQueryResponseDto
type CypherQueryResponseDto struct {
	Columns              []string             `json:"columns,omitempty"`
	Rows                 [][]interface{}      `json:"rows,omitempty"`
	Stats                *CypherQueryStatsDto `json:"stats,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CypherQueryResponseDto CypherQueryResponseDto

// NewCypherQueryResponseDto instantiates a new CypherQueryResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCypherQueryResponseDto() *CypherQueryResponseDto {
	this := CypherQueryResponseDto{}
	return &this
}

// NewCypherQueryResponseDtoWithDefaults instantiates a new CypherQueryResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCypherQueryResponseDtoWithDefaults() *CypherQueryResponseDto {
	this := CypherQueryResponseDto{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *CypherQueryResponseDto) GetColumns() []string {
	if o == nil || IsNil(o.Columns) {
		var ret []string
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryResponseDto) GetColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *CypherQueryResponseDto) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []string and assigns it to the Columns field.
func (o *CypherQueryResponseDto) SetColumns(v []string) {
	o.Columns = v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *CypherQueryResponseDto) GetRows() [][]interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret [][]interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryResponseDto) GetRowsOk() ([][]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *CypherQueryResponseDto) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given [][]interface{} and assigns it to the Rows field.
func (o *CypherQueryResponseDto) SetRows(v [][]interface{}) {
	o.Rows = v
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *CypherQueryResponseDto) GetStats() CypherQueryStatsDto {
	if o == nil || IsNil(o.Stats) {
		var ret CypherQueryStatsDto
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CypherQueryResponseDto) GetStatsOk() (*CypherQueryStatsDto, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *CypherQueryResponseDto) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given CypherQueryStatsDto and assigns it to the Stats field.
func (o *CypherQueryResponseDto) SetStats(v CypherQueryStatsDto) {
	o.Stats = &v
}

func (o CypherQueryResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CypherQueryResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CypherQueryResponseDto) UnmarshalJSON(data []byte) (err error) {
	varCypherQueryResponseDto := _CypherQueryResponseDto{}

	err = json.Unmarshal(data, &varCypherQueryResponseDto)

	if err != nil {
		return err
	}

	*o = CypherQueryResponseDto(varCypherQueryResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "columns")
		delete(additionalProperties, "rows")
		delete(additionalProperties, "stats")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCypherQueryResponseDto struct {
	value *CypherQueryResponseDto
	isSet bool
}

func (v NullableCypherQueryResponseDto) Get() *CypherQueryResponseDto {
	return v.value
}

func (v *NullableCypherQueryResponseDto) Set(val *CypherQueryResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCypherQueryResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCypherQueryResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCypherQueryResponseDto(val *CypherQueryResponseDto) *NullableCypherQueryResponseDto {
	return &NullableCypherQueryResponseDto{value: val, isSet: true}
}

func (v NullableCypherQueryResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCypherQueryResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
