/*
Asserts, Inc

Asserts Public API

API version: 2026.04.06-152933
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the GroupedEntityCountDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupedEntityCountDto{}

// GroupedEntityCountDto struct for GroupedEntityCountDto
type GroupedEntityCountDto struct {
	Total                int64             `json:"total"`
	WithInsights         *int64            `json:"withInsights,omitempty"`
	GroupedBy            map[string]string `json:"groupedBy,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupedEntityCountDto GroupedEntityCountDto

// NewGroupedEntityCountDto instantiates a new GroupedEntityCountDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupedEntityCountDto(total int64) *GroupedEntityCountDto {
	this := GroupedEntityCountDto{}
	this.Total = total
	return &this
}

// NewGroupedEntityCountDtoWithDefaults instantiates a new GroupedEntityCountDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupedEntityCountDtoWithDefaults() *GroupedEntityCountDto {
	this := GroupedEntityCountDto{}
	return &this
}

// GetTotal returns the Total field value
func (o *GroupedEntityCountDto) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GroupedEntityCountDto) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GroupedEntityCountDto) SetTotal(v int64) {
	o.Total = v
}

// GetWithInsights returns the WithInsights field value if set, zero value otherwise.
func (o *GroupedEntityCountDto) GetWithInsights() int64 {
	if o == nil || IsNil(o.WithInsights) {
		var ret int64
		return ret
	}
	return *o.WithInsights
}

// GetWithInsightsOk returns a tuple with the WithInsights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedEntityCountDto) GetWithInsightsOk() (*int64, bool) {
	if o == nil || IsNil(o.WithInsights) {
		return nil, false
	}
	return o.WithInsights, true
}

// HasWithInsights returns a boolean if a field has been set.
func (o *GroupedEntityCountDto) HasWithInsights() bool {
	if o != nil && !IsNil(o.WithInsights) {
		return true
	}

	return false
}

// SetWithInsights gets a reference to the given int64 and assigns it to the WithInsights field.
func (o *GroupedEntityCountDto) SetWithInsights(v int64) {
	o.WithInsights = &v
}

// GetGroupedBy returns the GroupedBy field value if set, zero value otherwise.
func (o *GroupedEntityCountDto) GetGroupedBy() map[string]string {
	if o == nil || IsNil(o.GroupedBy) {
		var ret map[string]string
		return ret
	}
	return o.GroupedBy
}

// GetGroupedByOk returns a tuple with the GroupedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupedEntityCountDto) GetGroupedByOk() (map[string]string, bool) {
	if o == nil || IsNil(o.GroupedBy) {
		return map[string]string{}, false
	}
	return o.GroupedBy, true
}

// HasGroupedBy returns a boolean if a field has been set.
func (o *GroupedEntityCountDto) HasGroupedBy() bool {
	if o != nil && !IsNil(o.GroupedBy) {
		return true
	}

	return false
}

// SetGroupedBy gets a reference to the given map[string]string and assigns it to the GroupedBy field.
func (o *GroupedEntityCountDto) SetGroupedBy(v map[string]string) {
	o.GroupedBy = v
}

func (o GroupedEntityCountDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupedEntityCountDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	if !IsNil(o.WithInsights) {
		toSerialize["withInsights"] = o.WithInsights
	}
	if !IsNil(o.GroupedBy) {
		toSerialize["groupedBy"] = o.GroupedBy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupedEntityCountDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varGroupedEntityCountDto := _GroupedEntityCountDto{}

	err = json.Unmarshal(data, &varGroupedEntityCountDto)

	if err != nil {
		return err
	}

	*o = GroupedEntityCountDto(varGroupedEntityCountDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "total")
		delete(additionalProperties, "withInsights")
		delete(additionalProperties, "groupedBy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupedEntityCountDto struct {
	value *GroupedEntityCountDto
	isSet bool
}

func (v NullableGroupedEntityCountDto) Get() *GroupedEntityCountDto {
	return v.value
}

func (v *NullableGroupedEntityCountDto) Set(val *GroupedEntityCountDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupedEntityCountDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupedEntityCountDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupedEntityCountDto(val *GroupedEntityCountDto) *NullableGroupedEntityCountDto {
	return &NullableGroupedEntityCountDto{value: val, isSet: true}
}

func (v NullableGroupedEntityCountDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupedEntityCountDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
