/*
Asserts, Inc

Asserts Public API

API version: 2026.02.11-155702
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the ImmutableMapStringString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImmutableMapStringString{}

// ImmutableMapStringString struct for ImmutableMapStringString
type ImmutableMapStringString struct {
	Empty                *bool `json:"empty,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ImmutableMapStringString ImmutableMapStringString

// NewImmutableMapStringString instantiates a new ImmutableMapStringString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImmutableMapStringString() *ImmutableMapStringString {
	this := ImmutableMapStringString{}
	return &this
}

// NewImmutableMapStringStringWithDefaults instantiates a new ImmutableMapStringString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImmutableMapStringStringWithDefaults() *ImmutableMapStringString {
	this := ImmutableMapStringString{}
	return &this
}

// GetEmpty returns the Empty field value if set, zero value otherwise.
func (o *ImmutableMapStringString) GetEmpty() bool {
	if o == nil || IsNil(o.Empty) {
		var ret bool
		return ret
	}
	return *o.Empty
}

// GetEmptyOk returns a tuple with the Empty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImmutableMapStringString) GetEmptyOk() (*bool, bool) {
	if o == nil || IsNil(o.Empty) {
		return nil, false
	}
	return o.Empty, true
}

// HasEmpty returns a boolean if a field has been set.
func (o *ImmutableMapStringString) HasEmpty() bool {
	if o != nil && !IsNil(o.Empty) {
		return true
	}

	return false
}

// SetEmpty gets a reference to the given bool and assigns it to the Empty field.
func (o *ImmutableMapStringString) SetEmpty(v bool) {
	o.Empty = &v
}

func (o ImmutableMapStringString) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImmutableMapStringString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Empty) {
		toSerialize["empty"] = o.Empty
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImmutableMapStringString) UnmarshalJSON(data []byte) (err error) {
	varImmutableMapStringString := _ImmutableMapStringString{}

	err = json.Unmarshal(data, &varImmutableMapStringString)

	if err != nil {
		return err
	}

	*o = ImmutableMapStringString(varImmutableMapStringString)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "empty")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImmutableMapStringString struct {
	value *ImmutableMapStringString
	isSet bool
}

func (v NullableImmutableMapStringString) Get() *ImmutableMapStringString {
	return v.value
}

func (v *NullableImmutableMapStringString) Set(val *ImmutableMapStringString) {
	v.value = val
	v.isSet = true
}

func (v NullableImmutableMapStringString) IsSet() bool {
	return v.isSet
}

func (v *NullableImmutableMapStringString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImmutableMapStringString(val *ImmutableMapStringString) *NullableImmutableMapStringString {
	return &NullableImmutableMapStringString{value: val, isSet: true}
}

func (v NullableImmutableMapStringString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImmutableMapStringString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
