/*
Asserts, Inc

Asserts Public API

API version: 2026.02.02-070551
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the ProfileConfigPriorityDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileConfigPriorityDto{}

// ProfileConfigPriorityDto struct for ProfileConfigPriorityDto
type ProfileConfigPriorityDto struct {
	Name                 *string `json:"name,omitempty"`
	Priority             *int32  `json:"priority,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProfileConfigPriorityDto ProfileConfigPriorityDto

// NewProfileConfigPriorityDto instantiates a new ProfileConfigPriorityDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileConfigPriorityDto() *ProfileConfigPriorityDto {
	this := ProfileConfigPriorityDto{}
	return &this
}

// NewProfileConfigPriorityDtoWithDefaults instantiates a new ProfileConfigPriorityDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileConfigPriorityDtoWithDefaults() *ProfileConfigPriorityDto {
	this := ProfileConfigPriorityDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProfileConfigPriorityDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileConfigPriorityDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProfileConfigPriorityDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProfileConfigPriorityDto) SetName(v string) {
	o.Name = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ProfileConfigPriorityDto) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileConfigPriorityDto) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ProfileConfigPriorityDto) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *ProfileConfigPriorityDto) SetPriority(v int32) {
	o.Priority = &v
}

func (o ProfileConfigPriorityDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileConfigPriorityDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProfileConfigPriorityDto) UnmarshalJSON(data []byte) (err error) {
	varProfileConfigPriorityDto := _ProfileConfigPriorityDto{}

	err = json.Unmarshal(data, &varProfileConfigPriorityDto)

	if err != nil {
		return err
	}

	*o = ProfileConfigPriorityDto(varProfileConfigPriorityDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "priority")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProfileConfigPriorityDto struct {
	value *ProfileConfigPriorityDto
	isSet bool
}

func (v NullableProfileConfigPriorityDto) Get() *ProfileConfigPriorityDto {
	return v.value
}

func (v *NullableProfileConfigPriorityDto) Set(val *ProfileConfigPriorityDto) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileConfigPriorityDto) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileConfigPriorityDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileConfigPriorityDto(val *ProfileConfigPriorityDto) *NullableProfileConfigPriorityDto {
	return &NullableProfileConfigPriorityDto{value: val, isSet: true}
}

func (v NullableProfileConfigPriorityDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileConfigPriorityDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
