/*
Asserts, Inc

Asserts Public API

API version: 2026.05.28-125801
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the EntityEventsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityEventsDto{}

// EntityEventsDto struct for EntityEventsDto
type EntityEventsDto struct {
	EntityType           *string           `json:"entityType,omitempty"`
	EntityName           *string           `json:"entityName,omitempty"`
	Scope                map[string]string `json:"scope,omitempty"`
	StartTime            *int64            `json:"startTime,omitempty"`
	EndTime              *int64            `json:"endTime,omitempty"`
	Events               []InfraEventDto   `json:"events,omitempty"`
	TotalCount           *int32            `json:"totalCount,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EntityEventsDto EntityEventsDto

// NewEntityEventsDto instantiates a new EntityEventsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityEventsDto() *EntityEventsDto {
	this := EntityEventsDto{}
	return &this
}

// NewEntityEventsDtoWithDefaults instantiates a new EntityEventsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityEventsDtoWithDefaults() *EntityEventsDto {
	this := EntityEventsDto{}
	return &this
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *EntityEventsDto) GetEntityType() string {
	if o == nil || IsNil(o.EntityType) {
		var ret string
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetEntityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EntityType) {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *EntityEventsDto) HasEntityType() bool {
	if o != nil && !IsNil(o.EntityType) {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given string and assigns it to the EntityType field.
func (o *EntityEventsDto) SetEntityType(v string) {
	o.EntityType = &v
}

// GetEntityName returns the EntityName field value if set, zero value otherwise.
func (o *EntityEventsDto) GetEntityName() string {
	if o == nil || IsNil(o.EntityName) {
		var ret string
		return ret
	}
	return *o.EntityName
}

// GetEntityNameOk returns a tuple with the EntityName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetEntityNameOk() (*string, bool) {
	if o == nil || IsNil(o.EntityName) {
		return nil, false
	}
	return o.EntityName, true
}

// HasEntityName returns a boolean if a field has been set.
func (o *EntityEventsDto) HasEntityName() bool {
	if o != nil && !IsNil(o.EntityName) {
		return true
	}

	return false
}

// SetEntityName gets a reference to the given string and assigns it to the EntityName field.
func (o *EntityEventsDto) SetEntityName(v string) {
	o.EntityName = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *EntityEventsDto) GetScope() map[string]string {
	if o == nil || IsNil(o.Scope) {
		var ret map[string]string
		return ret
	}
	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetScopeOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Scope) {
		return map[string]string{}, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *EntityEventsDto) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given map[string]string and assigns it to the Scope field.
func (o *EntityEventsDto) SetScope(v map[string]string) {
	o.Scope = v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *EntityEventsDto) GetStartTime() int64 {
	if o == nil || IsNil(o.StartTime) {
		var ret int64
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetStartTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *EntityEventsDto) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int64 and assigns it to the StartTime field.
func (o *EntityEventsDto) SetStartTime(v int64) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *EntityEventsDto) GetEndTime() int64 {
	if o == nil || IsNil(o.EndTime) {
		var ret int64
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetEndTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *EntityEventsDto) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given int64 and assigns it to the EndTime field.
func (o *EntityEventsDto) SetEndTime(v int64) {
	o.EndTime = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *EntityEventsDto) GetEvents() []InfraEventDto {
	if o == nil || IsNil(o.Events) {
		var ret []InfraEventDto
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetEventsOk() ([]InfraEventDto, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *EntityEventsDto) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []InfraEventDto and assigns it to the Events field.
func (o *EntityEventsDto) SetEvents(v []InfraEventDto) {
	o.Events = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *EntityEventsDto) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityEventsDto) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *EntityEventsDto) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *EntityEventsDto) SetTotalCount(v int32) {
	o.TotalCount = &v
}

func (o EntityEventsDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityEventsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EntityType) {
		toSerialize["entityType"] = o.EntityType
	}
	if !IsNil(o.EntityName) {
		toSerialize["entityName"] = o.EntityName
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EntityEventsDto) UnmarshalJSON(data []byte) (err error) {
	varEntityEventsDto := _EntityEventsDto{}

	err = json.Unmarshal(data, &varEntityEventsDto)

	if err != nil {
		return err
	}

	*o = EntityEventsDto(varEntityEventsDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "entityType")
		delete(additionalProperties, "entityName")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "startTime")
		delete(additionalProperties, "endTime")
		delete(additionalProperties, "events")
		delete(additionalProperties, "totalCount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntityEventsDto struct {
	value *EntityEventsDto
	isSet bool
}

func (v NullableEntityEventsDto) Get() *EntityEventsDto {
	return v.value
}

func (v *NullableEntityEventsDto) Set(val *EntityEventsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityEventsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityEventsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityEventsDto(val *EntityEventsDto) *NullableEntityEventsDto {
	return &NullableEntityEventsDto{value: val, isSet: true}
}

func (v NullableEntityEventsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityEventsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
