/*
Asserts, Inc

Asserts Public API

API version: 2.68.0
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package systemschema

import (
	"encoding/json"
	"fmt"
)

// ApiQuerySyntaxErrorType the model 'ApiQuerySyntaxErrorType'
type ApiQuerySyntaxErrorType string

// List of ApiQuerySyntaxErrorType
const (
	API_QUERY_SYNTAX_ERROR ApiQuerySyntaxErrorType = "ApiQuerySyntaxError"
)

// All allowed values of ApiQuerySyntaxErrorType enum
var AllowedApiQuerySyntaxErrorTypeEnumValues = []ApiQuerySyntaxErrorType{
	"ApiQuerySyntaxError",
}

func (v *ApiQuerySyntaxErrorType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ApiQuerySyntaxErrorType(value)
	for _, existing := range AllowedApiQuerySyntaxErrorTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ApiQuerySyntaxErrorType", value)
}

// NewApiQuerySyntaxErrorTypeFromValue returns a pointer to a valid ApiQuerySyntaxErrorType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewApiQuerySyntaxErrorTypeFromValue(v string) (*ApiQuerySyntaxErrorType, error) {
	ev := ApiQuerySyntaxErrorType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ApiQuerySyntaxErrorType: valid values are %v", v, AllowedApiQuerySyntaxErrorTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ApiQuerySyntaxErrorType) IsValid() bool {
	for _, existing := range AllowedApiQuerySyntaxErrorTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ApiQuerySyntaxErrorType value
func (v ApiQuerySyntaxErrorType) Ptr() *ApiQuerySyntaxErrorType {
	return &v
}

type NullableApiQuerySyntaxErrorType struct {
	value *ApiQuerySyntaxErrorType
	isSet bool
}

func (v NullableApiQuerySyntaxErrorType) Get() *ApiQuerySyntaxErrorType {
	return v.value
}

func (v *NullableApiQuerySyntaxErrorType) Set(val *ApiQuerySyntaxErrorType) {
	v.value = val
	v.isSet = true
}

func (v NullableApiQuerySyntaxErrorType) IsSet() bool {
	return v.isSet
}

func (v *NullableApiQuerySyntaxErrorType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiQuerySyntaxErrorType(val *ApiQuerySyntaxErrorType) *NullableApiQuerySyntaxErrorType {
	return &NullableApiQuerySyntaxErrorType{value: val, isSet: true}
}

func (v NullableApiQuerySyntaxErrorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiQuerySyntaxErrorType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
