/*
Asserts, Inc

Asserts Public API

API version: 2026.08.13-141456
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package systemschema

import (
	"encoding/json"
)

// checks if the SystemKgSchemaRefListDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemKgSchemaRefListDto{}

// SystemKgSchemaRefListDto struct for SystemKgSchemaRefListDto
type SystemKgSchemaRefListDto struct {
	Schemas              []SchemaDomainDto `json:"schemas,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SystemKgSchemaRefListDto SystemKgSchemaRefListDto

// NewSystemKgSchemaRefListDto instantiates a new SystemKgSchemaRefListDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemKgSchemaRefListDto() *SystemKgSchemaRefListDto {
	this := SystemKgSchemaRefListDto{}
	return &this
}

// NewSystemKgSchemaRefListDtoWithDefaults instantiates a new SystemKgSchemaRefListDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemKgSchemaRefListDtoWithDefaults() *SystemKgSchemaRefListDto {
	this := SystemKgSchemaRefListDto{}
	return &this
}

// GetSchemas returns the Schemas field value if set, zero value otherwise.
func (o *SystemKgSchemaRefListDto) GetSchemas() []SchemaDomainDto {
	if o == nil || IsNil(o.Schemas) {
		var ret []SchemaDomainDto
		return ret
	}
	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemKgSchemaRefListDto) GetSchemasOk() ([]SchemaDomainDto, bool) {
	if o == nil || IsNil(o.Schemas) {
		return nil, false
	}
	return o.Schemas, true
}

// HasSchemas returns a boolean if a field has been set.
func (o *SystemKgSchemaRefListDto) HasSchemas() bool {
	if o != nil && !IsNil(o.Schemas) {
		return true
	}

	return false
}

// SetSchemas gets a reference to the given []SchemaDomainDto and assigns it to the Schemas field.
func (o *SystemKgSchemaRefListDto) SetSchemas(v []SchemaDomainDto) {
	o.Schemas = v
}

func (o SystemKgSchemaRefListDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemKgSchemaRefListDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schemas) {
		toSerialize["schemas"] = o.Schemas
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemKgSchemaRefListDto) UnmarshalJSON(data []byte) (err error) {
	varSystemKgSchemaRefListDto := _SystemKgSchemaRefListDto{}

	err = json.Unmarshal(data, &varSystemKgSchemaRefListDto)

	if err != nil {
		return err
	}

	*o = SystemKgSchemaRefListDto(varSystemKgSchemaRefListDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schemas")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemKgSchemaRefListDto struct {
	value *SystemKgSchemaRefListDto
	isSet bool
}

func (v NullableSystemKgSchemaRefListDto) Get() *SystemKgSchemaRefListDto {
	return v.value
}

func (v *NullableSystemKgSchemaRefListDto) Set(val *SystemKgSchemaRefListDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemKgSchemaRefListDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemKgSchemaRefListDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemKgSchemaRefListDto(val *SystemKgSchemaRefListDto) *NullableSystemKgSchemaRefListDto {
	return &NullableSystemKgSchemaRefListDto{value: val, isSet: true}
}

func (v NullableSystemKgSchemaRefListDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemKgSchemaRefListDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
