/*
Asserts, Inc

Asserts Public API

API version: 2026.08.13-141456
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package systemschema

import (
	"encoding/json"
)

// checks if the SchemaRelationshipTypeDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaRelationshipTypeDto{}

// SchemaRelationshipTypeDto struct for SchemaRelationshipTypeDto
type SchemaRelationshipTypeDto struct {
	Name                 string              `json:"name" validate:"regexp=^[A-Z][A-Z0-9_]*$"`
	Description          string              `json:"description"`
	RetentionDays        *int32              `json:"retentionDays,omitempty"`
	Aliases              []string            `json:"aliases,omitempty"`
	Label                map[string]string   `json:"label,omitempty"`
	Inverse              *string             `json:"inverse,omitempty" validate:"regexp=^[A-Z][A-Z0-9_]*$"`
	Characteristics      []string            `json:"characteristics,omitempty"`
	From                 SchemaEndpointDto   `json:"from"`
	To                   SchemaEndpointDto   `json:"to"`
	Properties           []SchemaPropertyDto `json:"properties,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SchemaRelationshipTypeDto SchemaRelationshipTypeDto

// NewSchemaRelationshipTypeDto instantiates a new SchemaRelationshipTypeDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaRelationshipTypeDto(name string, description string, from SchemaEndpointDto, to SchemaEndpointDto) *SchemaRelationshipTypeDto {
	this := SchemaRelationshipTypeDto{}
	this.Name = name
	this.Description = description
	this.From = from
	this.To = to
	return &this
}

// NewSchemaRelationshipTypeDtoWithDefaults instantiates a new SchemaRelationshipTypeDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaRelationshipTypeDtoWithDefaults() *SchemaRelationshipTypeDto {
	this := SchemaRelationshipTypeDto{}
	return &this
}

// GetName returns the Name field value
func (o *SchemaRelationshipTypeDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SchemaRelationshipTypeDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SchemaRelationshipTypeDto) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SchemaRelationshipTypeDto) SetDescription(v string) {
	o.Description = v
}

// GetRetentionDays returns the RetentionDays field value if set, zero value otherwise.
func (o *SchemaRelationshipTypeDto) GetRetentionDays() int32 {
	if o == nil || IsNil(o.RetentionDays) {
		var ret int32
		return ret
	}
	return *o.RetentionDays
}

// GetRetentionDaysOk returns a tuple with the RetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.RetentionDays) {
		return nil, false
	}
	return o.RetentionDays, true
}

// HasRetentionDays returns a boolean if a field has been set.
func (o *SchemaRelationshipTypeDto) HasRetentionDays() bool {
	if o != nil && !IsNil(o.RetentionDays) {
		return true
	}

	return false
}

// SetRetentionDays gets a reference to the given int32 and assigns it to the RetentionDays field.
func (o *SchemaRelationshipTypeDto) SetRetentionDays(v int32) {
	o.RetentionDays = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *SchemaRelationshipTypeDto) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *SchemaRelationshipTypeDto) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *SchemaRelationshipTypeDto) SetAliases(v []string) {
	o.Aliases = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SchemaRelationshipTypeDto) GetLabel() map[string]string {
	if o == nil || IsNil(o.Label) {
		var ret map[string]string
		return ret
	}
	return o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetLabelOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Label) {
		return map[string]string{}, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SchemaRelationshipTypeDto) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given map[string]string and assigns it to the Label field.
func (o *SchemaRelationshipTypeDto) SetLabel(v map[string]string) {
	o.Label = v
}

// GetInverse returns the Inverse field value if set, zero value otherwise.
func (o *SchemaRelationshipTypeDto) GetInverse() string {
	if o == nil || IsNil(o.Inverse) {
		var ret string
		return ret
	}
	return *o.Inverse
}

// GetInverseOk returns a tuple with the Inverse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetInverseOk() (*string, bool) {
	if o == nil || IsNil(o.Inverse) {
		return nil, false
	}
	return o.Inverse, true
}

// HasInverse returns a boolean if a field has been set.
func (o *SchemaRelationshipTypeDto) HasInverse() bool {
	if o != nil && !IsNil(o.Inverse) {
		return true
	}

	return false
}

// SetInverse gets a reference to the given string and assigns it to the Inverse field.
func (o *SchemaRelationshipTypeDto) SetInverse(v string) {
	o.Inverse = &v
}

// GetCharacteristics returns the Characteristics field value if set, zero value otherwise.
func (o *SchemaRelationshipTypeDto) GetCharacteristics() []string {
	if o == nil || IsNil(o.Characteristics) {
		var ret []string
		return ret
	}
	return o.Characteristics
}

// GetCharacteristicsOk returns a tuple with the Characteristics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetCharacteristicsOk() ([]string, bool) {
	if o == nil || IsNil(o.Characteristics) {
		return nil, false
	}
	return o.Characteristics, true
}

// HasCharacteristics returns a boolean if a field has been set.
func (o *SchemaRelationshipTypeDto) HasCharacteristics() bool {
	if o != nil && !IsNil(o.Characteristics) {
		return true
	}

	return false
}

// SetCharacteristics gets a reference to the given []string and assigns it to the Characteristics field.
func (o *SchemaRelationshipTypeDto) SetCharacteristics(v []string) {
	o.Characteristics = v
}

// GetFrom returns the From field value
func (o *SchemaRelationshipTypeDto) GetFrom() SchemaEndpointDto {
	if o == nil {
		var ret SchemaEndpointDto
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetFromOk() (*SchemaEndpointDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *SchemaRelationshipTypeDto) SetFrom(v SchemaEndpointDto) {
	o.From = v
}

// GetTo returns the To field value
func (o *SchemaRelationshipTypeDto) GetTo() SchemaEndpointDto {
	if o == nil {
		var ret SchemaEndpointDto
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetToOk() (*SchemaEndpointDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *SchemaRelationshipTypeDto) SetTo(v SchemaEndpointDto) {
	o.To = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *SchemaRelationshipTypeDto) GetProperties() []SchemaPropertyDto {
	if o == nil || IsNil(o.Properties) {
		var ret []SchemaPropertyDto
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaRelationshipTypeDto) GetPropertiesOk() ([]SchemaPropertyDto, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *SchemaRelationshipTypeDto) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []SchemaPropertyDto and assigns it to the Properties field.
func (o *SchemaRelationshipTypeDto) SetProperties(v []SchemaPropertyDto) {
	o.Properties = v
}

func (o SchemaRelationshipTypeDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaRelationshipTypeDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.RetentionDays) {
		toSerialize["retentionDays"] = o.RetentionDays
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Inverse) {
		toSerialize["inverse"] = o.Inverse
	}
	if !IsNil(o.Characteristics) {
		toSerialize["characteristics"] = o.Characteristics
	}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaRelationshipTypeDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSchemaRelationshipTypeDto := _SchemaRelationshipTypeDto{}

	err = json.Unmarshal(data, &varSchemaRelationshipTypeDto)

	if err != nil {
		return err
	}

	*o = SchemaRelationshipTypeDto(varSchemaRelationshipTypeDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "retentionDays")
		delete(additionalProperties, "aliases")
		delete(additionalProperties, "label")
		delete(additionalProperties, "inverse")
		delete(additionalProperties, "characteristics")
		delete(additionalProperties, "from")
		delete(additionalProperties, "to")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaRelationshipTypeDto struct {
	value *SchemaRelationshipTypeDto
	isSet bool
}

func (v NullableSchemaRelationshipTypeDto) Get() *SchemaRelationshipTypeDto {
	return v.value
}

func (v *NullableSchemaRelationshipTypeDto) Set(val *SchemaRelationshipTypeDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaRelationshipTypeDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaRelationshipTypeDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaRelationshipTypeDto(val *SchemaRelationshipTypeDto) *NullableSchemaRelationshipTypeDto {
	return &NullableSchemaRelationshipTypeDto{value: val, isSet: true}
}

func (v NullableSchemaRelationshipTypeDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaRelationshipTypeDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
