/*
Asserts, Inc

Asserts Public API

API version: v2.38.0
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package systemschema

import (
	"encoding/json"
)

// checks if the SchemaEntityTypeDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaEntityTypeDto{}

// SchemaEntityTypeDto struct for SchemaEntityTypeDto
type SchemaEntityTypeDto struct {
	Name                 string              `json:"name" validate:"regexp=^[A-Z][A-Za-z0-9]*$"`
	Description          string              `json:"description"`
	RetentionDays        *int32              `json:"retentionDays,omitempty"`
	Aliases              []string            `json:"aliases,omitempty"`
	Label                map[string]string   `json:"label,omitempty"`
	ScopeKeys            []SchemaScopeKeyDto `json:"scopeKeys,omitempty"`
	Properties           []SchemaPropertyDto `json:"properties,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SchemaEntityTypeDto SchemaEntityTypeDto

// NewSchemaEntityTypeDto instantiates a new SchemaEntityTypeDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaEntityTypeDto(name string, description string) *SchemaEntityTypeDto {
	this := SchemaEntityTypeDto{}
	this.Name = name
	this.Description = description
	return &this
}

// NewSchemaEntityTypeDtoWithDefaults instantiates a new SchemaEntityTypeDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaEntityTypeDtoWithDefaults() *SchemaEntityTypeDto {
	this := SchemaEntityTypeDto{}
	return &this
}

// GetName returns the Name field value
func (o *SchemaEntityTypeDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SchemaEntityTypeDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SchemaEntityTypeDto) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SchemaEntityTypeDto) SetDescription(v string) {
	o.Description = v
}

// GetRetentionDays returns the RetentionDays field value if set, zero value otherwise.
func (o *SchemaEntityTypeDto) GetRetentionDays() int32 {
	if o == nil || IsNil(o.RetentionDays) {
		var ret int32
		return ret
	}
	return *o.RetentionDays
}

// GetRetentionDaysOk returns a tuple with the RetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.RetentionDays) {
		return nil, false
	}
	return o.RetentionDays, true
}

// HasRetentionDays returns a boolean if a field has been set.
func (o *SchemaEntityTypeDto) HasRetentionDays() bool {
	if o != nil && !IsNil(o.RetentionDays) {
		return true
	}

	return false
}

// SetRetentionDays gets a reference to the given int32 and assigns it to the RetentionDays field.
func (o *SchemaEntityTypeDto) SetRetentionDays(v int32) {
	o.RetentionDays = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *SchemaEntityTypeDto) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *SchemaEntityTypeDto) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *SchemaEntityTypeDto) SetAliases(v []string) {
	o.Aliases = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SchemaEntityTypeDto) GetLabel() map[string]string {
	if o == nil || IsNil(o.Label) {
		var ret map[string]string
		return ret
	}
	return o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetLabelOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Label) {
		return map[string]string{}, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SchemaEntityTypeDto) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given map[string]string and assigns it to the Label field.
func (o *SchemaEntityTypeDto) SetLabel(v map[string]string) {
	o.Label = v
}

// GetScopeKeys returns the ScopeKeys field value if set, zero value otherwise.
func (o *SchemaEntityTypeDto) GetScopeKeys() []SchemaScopeKeyDto {
	if o == nil || IsNil(o.ScopeKeys) {
		var ret []SchemaScopeKeyDto
		return ret
	}
	return o.ScopeKeys
}

// GetScopeKeysOk returns a tuple with the ScopeKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetScopeKeysOk() ([]SchemaScopeKeyDto, bool) {
	if o == nil || IsNil(o.ScopeKeys) {
		return nil, false
	}
	return o.ScopeKeys, true
}

// HasScopeKeys returns a boolean if a field has been set.
func (o *SchemaEntityTypeDto) HasScopeKeys() bool {
	if o != nil && !IsNil(o.ScopeKeys) {
		return true
	}

	return false
}

// SetScopeKeys gets a reference to the given []SchemaScopeKeyDto and assigns it to the ScopeKeys field.
func (o *SchemaEntityTypeDto) SetScopeKeys(v []SchemaScopeKeyDto) {
	o.ScopeKeys = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *SchemaEntityTypeDto) GetProperties() []SchemaPropertyDto {
	if o == nil || IsNil(o.Properties) {
		var ret []SchemaPropertyDto
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntityTypeDto) GetPropertiesOk() ([]SchemaPropertyDto, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *SchemaEntityTypeDto) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []SchemaPropertyDto and assigns it to the Properties field.
func (o *SchemaEntityTypeDto) SetProperties(v []SchemaPropertyDto) {
	o.Properties = v
}

func (o SchemaEntityTypeDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaEntityTypeDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.RetentionDays) {
		toSerialize["retentionDays"] = o.RetentionDays
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.ScopeKeys) {
		toSerialize["scopeKeys"] = o.ScopeKeys
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaEntityTypeDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSchemaEntityTypeDto := _SchemaEntityTypeDto{}

	err = json.Unmarshal(data, &varSchemaEntityTypeDto)

	if err != nil {
		return err
	}

	*o = SchemaEntityTypeDto(varSchemaEntityTypeDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "retentionDays")
		delete(additionalProperties, "aliases")
		delete(additionalProperties, "label")
		delete(additionalProperties, "scopeKeys")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaEntityTypeDto struct {
	value *SchemaEntityTypeDto
	isSet bool
}

func (v NullableSchemaEntityTypeDto) Get() *SchemaEntityTypeDto {
	return v.value
}

func (v *NullableSchemaEntityTypeDto) Set(val *SchemaEntityTypeDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaEntityTypeDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaEntityTypeDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaEntityTypeDto(val *SchemaEntityTypeDto) *NullableSchemaEntityTypeDto {
	return &NullableSchemaEntityTypeDto{value: val, isSet: true}
}

func (v NullableSchemaEntityTypeDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaEntityTypeDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
