/*
Asserts, Inc

Asserts Public API

API version: v2.38.0
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package systemschema

import (
	"encoding/json"
)

// checks if the SchemaEndpointDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaEndpointDto{}

// SchemaEndpointDto struct for SchemaEndpointDto
type SchemaEndpointDto struct {
	Types                []string `json:"types"`
	Cardinality          *string  `json:"cardinality,omitempty" validate:"regexp=^(one|many)$"`
	AdditionalProperties map[string]interface{}
}

type _SchemaEndpointDto SchemaEndpointDto

// NewSchemaEndpointDto instantiates a new SchemaEndpointDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaEndpointDto(types []string) *SchemaEndpointDto {
	this := SchemaEndpointDto{}
	this.Types = types
	return &this
}

// NewSchemaEndpointDtoWithDefaults instantiates a new SchemaEndpointDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaEndpointDtoWithDefaults() *SchemaEndpointDto {
	this := SchemaEndpointDto{}
	return &this
}

// GetTypes returns the Types field value
func (o *SchemaEndpointDto) GetTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *SchemaEndpointDto) GetTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *SchemaEndpointDto) SetTypes(v []string) {
	o.Types = v
}

// GetCardinality returns the Cardinality field value if set, zero value otherwise.
func (o *SchemaEndpointDto) GetCardinality() string {
	if o == nil || IsNil(o.Cardinality) {
		var ret string
		return ret
	}
	return *o.Cardinality
}

// GetCardinalityOk returns a tuple with the Cardinality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEndpointDto) GetCardinalityOk() (*string, bool) {
	if o == nil || IsNil(o.Cardinality) {
		return nil, false
	}
	return o.Cardinality, true
}

// HasCardinality returns a boolean if a field has been set.
func (o *SchemaEndpointDto) HasCardinality() bool {
	if o != nil && !IsNil(o.Cardinality) {
		return true
	}

	return false
}

// SetCardinality gets a reference to the given string and assigns it to the Cardinality field.
func (o *SchemaEndpointDto) SetCardinality(v string) {
	o.Cardinality = &v
}

func (o SchemaEndpointDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaEndpointDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["types"] = o.Types
	if !IsNil(o.Cardinality) {
		toSerialize["cardinality"] = o.Cardinality
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaEndpointDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSchemaEndpointDto := _SchemaEndpointDto{}

	err = json.Unmarshal(data, &varSchemaEndpointDto)

	if err != nil {
		return err
	}

	*o = SchemaEndpointDto(varSchemaEndpointDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "types")
		delete(additionalProperties, "cardinality")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaEndpointDto struct {
	value *SchemaEndpointDto
	isSet bool
}

func (v NullableSchemaEndpointDto) Get() *SchemaEndpointDto {
	return v.value
}

func (v *NullableSchemaEndpointDto) Set(val *SchemaEndpointDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaEndpointDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaEndpointDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaEndpointDto(val *SchemaEndpointDto) *NullableSchemaEndpointDto {
	return &NullableSchemaEndpointDto{value: val, isSet: true}
}

func (v NullableSchemaEndpointDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaEndpointDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
