/*
Asserts, Inc

Asserts Public API

API version: 0.0.0
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package systemschema

import (
	"encoding/json"
)

// checks if the SchemaDomainDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaDomainDto{}

// SchemaDomainDto struct for SchemaDomainDto
type SchemaDomainDto struct {
	Name                 string  `json:"name" validate:"regexp=^[a-z][a-z0-9]*$"`
	DisplayName          *string `json:"displayName,omitempty"`
	Version              string  `json:"version" validate:"regexp=^v[0-9]+(alpha[0-9]+|beta[0-9]+)?$"`
	AdditionalProperties map[string]interface{}
}

type _SchemaDomainDto SchemaDomainDto

// NewSchemaDomainDto instantiates a new SchemaDomainDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaDomainDto(name string, version string) *SchemaDomainDto {
	this := SchemaDomainDto{}
	this.Name = name
	this.Version = version
	return &this
}

// NewSchemaDomainDtoWithDefaults instantiates a new SchemaDomainDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaDomainDtoWithDefaults() *SchemaDomainDto {
	this := SchemaDomainDto{}
	return &this
}

// GetName returns the Name field value
func (o *SchemaDomainDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SchemaDomainDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SchemaDomainDto) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *SchemaDomainDto) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaDomainDto) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *SchemaDomainDto) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *SchemaDomainDto) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetVersion returns the Version field value
func (o *SchemaDomainDto) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SchemaDomainDto) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SchemaDomainDto) SetVersion(v string) {
	o.Version = v
}

func (o SchemaDomainDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaDomainDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	toSerialize["version"] = o.Version

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaDomainDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSchemaDomainDto := _SchemaDomainDto{}

	err = json.Unmarshal(data, &varSchemaDomainDto)

	if err != nil {
		return err
	}

	*o = SchemaDomainDto(varSchemaDomainDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaDomainDto struct {
	value *SchemaDomainDto
	isSet bool
}

func (v NullableSchemaDomainDto) Get() *SchemaDomainDto {
	return v.value
}

func (v *NullableSchemaDomainDto) Set(val *SchemaDomainDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaDomainDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaDomainDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaDomainDto(val *SchemaDomainDto) *NullableSchemaDomainDto {
	return &NullableSchemaDomainDto{value: val, isSet: true}
}

func (v NullableSchemaDomainDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaDomainDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
