/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2.53.4
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  ConnectedEntitiesResponseDto,
  EntityReadResponseDto,
} from '../models/index';

export interface LookupConnectedEntitiesRequest {
    namespace: string;
    type: string;
    name: string;
    domain?: string;
    connectedType?: string;
    limit?: number;
    offset?: number;
    scope?: { [key: string]: string; };
    xScopeOrgID?: string;
}

export interface LookupEntityRequest {
    namespace: string;
    type: string;
    name: string;
    domain?: string;
    scope?: { [key: string]: string; };
    xScopeOrgID?: string;
}

/**
 * 
 */
export class KnowledgeGraphReadAPIApi extends runtime.BaseAPI {

    /**
     * Lists entities with at least one relationship to the anchor entity addressed by domain + type + name + exact scope; optionally filtered to one connected entity type. Expired connections are included with active: false. Results are ordered by name, with identity tiebreakers (type, domain, scope) for stable pagination.
     * Get entities connected to the entity with the given identity
     */
    async lookupConnectedEntitiesRaw(requestParameters: LookupConnectedEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectedEntitiesResponseDto>> {
        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling lookupConnectedEntities().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling lookupConnectedEntities().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling lookupConnectedEntities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['domain'] != null) {
            queryParameters['domain'] = requestParameters['domain'];
        }

        if (requestParameters['connectedType'] != null) {
            queryParameters['connected_type'] = requestParameters['connectedType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/apis/kg.grafana.com/v1alpha1/namespaces/{namespace}/entities/connected`.replace(`{${"namespace"}}`, encodeURIComponent(String(requestParameters['namespace']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Lists entities with at least one relationship to the anchor entity addressed by domain + type + name + exact scope; optionally filtered to one connected entity type. Expired connections are included with active: false. Results are ordered by name, with identity tiebreakers (type, domain, scope) for stable pagination.
     * Get entities connected to the entity with the given identity
     */
    async lookupConnectedEntities(requestParameters: LookupConnectedEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectedEntitiesResponseDto> {
        const response = await this.lookupConnectedEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolves a single entity by domain + type + name + exact scope (scope[key]=value query params). The scope must be the entity\'s complete scope; a subset of its scope keys does not match. Omit scope for scope-less entities and domain for the default telemetry domain.
     * Get one entity by its identity
     */
    async lookupEntityRaw(requestParameters: LookupEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityReadResponseDto>> {
        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling lookupEntity().'
            );
        }

        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling lookupEntity().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling lookupEntity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['domain'] != null) {
            queryParameters['domain'] = requestParameters['domain'];
        }

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/apis/kg.grafana.com/v1alpha1/namespaces/{namespace}/entities`.replace(`{${"namespace"}}`, encodeURIComponent(String(requestParameters['namespace']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Resolves a single entity by domain + type + name + exact scope (scope[key]=value query params). The scope must be the entity\'s complete scope; a subset of its scope keys does not match. Omit scope for scope-less entities and domain for the default telemetry domain.
     * Get one entity by its identity
     */
    async lookupEntity(requestParameters: LookupEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityReadResponseDto> {
        const response = await this.lookupEntityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
