/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2.53.4
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  SystemKgSchemaBundleDto,
  SystemKgSchemaRefListDto,
} from '../models/index';

export interface GetRequest {
    domain: string;
    version: string;
}

/**
 * 
 */
export class SystemKgSchemaAPIApi extends runtime.BaseAPI {

    /**
     * Returns the full schema bundle stored for the given domain/version key.
     * Get a system schema bundle by domain and version
     */
    async getRaw(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemKgSchemaBundleDto>> {
        if (requestParameters['domain'] == null) {
            throw new runtime.RequiredError(
                'domain',
                'Required parameter "domain" was null or undefined when calling get().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/apis/kg.grafana.com/v1alpha1/systemschemas/{domain}/{version}`.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters['domain']))).replace(`{${"version"}}`, encodeURIComponent(String(requestParameters['version']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the full schema bundle stored for the given domain/version key.
     * Get a system schema bundle by domain and version
     */
    async get(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemKgSchemaBundleDto> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a wrapped list of domain/version/displayName refs for all stored system schemas.
     * List all system schema references
     */
    async listRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemKgSchemaRefListDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/apis/kg.grafana.com/v1alpha1/systemschemas`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a wrapped list of domain/version/displayName refs for all stored system schemas.
     * List all system schema references
     */
    async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemKgSchemaRefListDto> {
        const response = await this.listRaw(initOverrides);
        return await response.value();
    }

}
