/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlertConfigDto,
  AlertConfigsDto,
  ApiError,
  DisabledAlertConfigDto,
  DisabledAlertConfigsDto,
  PrometheusRuleGroupDto,
} from '../models/index';

export interface DeleteAlertConfigRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface DeleteDisabledAlertConfigRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface GetAllAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetAllDisabledAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetDisabledHealthAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetDisabledRequestAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetDisabledResourceAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetFailureRuleGroupsRequest {
    customFailureRules?: string;
    allFailureRuleGroups?: string;
    xScopeOrgID?: string;
}

export interface GetHealthAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetRequestAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetResourceAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface GetSloAlertConfigsRequest {
    xScopeOrgID?: string;
}

export interface PutAlertConfigRequest {
    alertConfigDto: AlertConfigDto;
    xScopeOrgID?: string;
}

export interface PutAlertConfigsRequest {
    alertConfigsDto: AlertConfigsDto;
    xScopeOrgID?: string;
}

export interface PutDisabledAlertConfigRequest {
    disabledAlertConfigDto: DisabledAlertConfigDto;
    xScopeOrgID?: string;
}

export interface PutDisabledAlertConfigsRequest {
    disabledAlertConfigsDto: DisabledAlertConfigsDto;
    xScopeOrgID?: string;
}

export interface ValidateAlertConfigRequest {
    alertConfigDto: AlertConfigDto;
    xScopeOrgID?: string;
}

export interface ValidateAlertConfigsRequest {
    alertConfigsDto: AlertConfigsDto;
    xScopeOrgID?: string;
}

export interface ValidateDisabledAlertConfigRequest {
    disabledAlertConfigDto: DisabledAlertConfigDto;
    xScopeOrgID?: string;
}

export interface ValidateDisabledAlertConfigsRequest {
    disabledAlertConfigsDto: DisabledAlertConfigsDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class AlertConfigurationApi extends runtime.BaseAPI {

    /**
     * Deletes a specific alert configuration identified by its name.
     * Delete an alert configuration by name
     */
    async deleteAlertConfigRaw(requestParameters: DeleteAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteAlertConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alert/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a specific alert configuration identified by its name.
     * Delete an alert configuration by name
     */
    async deleteAlertConfig(requestParameters: DeleteAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAlertConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Deletes a \'disabled\' configuration, which re-enables the alert.
     * Re-enable an alert configuration by name
     */
    async deleteDisabledAlertConfigRaw(requestParameters: DeleteDisabledAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteDisabledAlertConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alert/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a \'disabled\' configuration, which re-enables the alert.
     * Re-enable an alert configuration by name
     */
    async deleteDisabledAlertConfig(requestParameters: DeleteDisabledAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDisabledAlertConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a list of all alert configurations for the tenant.
     * Get all alert configurations
     */
    async getAllAlertConfigsRaw(requestParameters: GetAllAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves a list of all alert configurations for the tenant.
     * Get all alert configurations
     */
    async getAllAlertConfigs(requestParameters: GetAllAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertConfigsDto> {
        const response = await this.getAllAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a list of all currently disabled alert configurations for the tenant.
     * Get all disabled alert configurations
     */
    async getAllDisabledAlertConfigsRaw(requestParameters: GetAllDisabledAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisabledAlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alerts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves a list of all currently disabled alert configurations for the tenant.
     * Get all disabled alert configurations
     */
    async getAllDisabledAlertConfigs(requestParameters: GetAllDisabledAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisabledAlertConfigsDto> {
        const response = await this.getAllDisabledAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves disabled alert configurations related to system health.
     * Get disabled health-based alert configurations
     */
    async getDisabledHealthAlertConfigsRaw(requestParameters: GetDisabledHealthAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisabledAlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alerts/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves disabled alert configurations related to system health.
     * Get disabled health-based alert configurations
     */
    async getDisabledHealthAlertConfigs(requestParameters: GetDisabledHealthAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisabledAlertConfigsDto> {
        const response = await this.getDisabledHealthAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves disabled alert configurations specifically for requests.
     * Get disabled request-based alert configurations
     */
    async getDisabledRequestAlertConfigsRaw(requestParameters: GetDisabledRequestAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisabledAlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alerts/request`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves disabled alert configurations specifically for requests.
     * Get disabled request-based alert configurations
     */
    async getDisabledRequestAlertConfigs(requestParameters: GetDisabledRequestAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisabledAlertConfigsDto> {
        const response = await this.getDisabledRequestAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves disabled alert configurations specifically for resources.
     * Get disabled resource-based alert configurations
     */
    async getDisabledResourceAlertConfigsRaw(requestParameters: GetDisabledResourceAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DisabledAlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alerts/resource`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves disabled alert configurations specifically for resources.
     * Get disabled resource-based alert configurations
     */
    async getDisabledResourceAlertConfigs(requestParameters: GetDisabledResourceAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DisabledAlertConfigsDto> {
        const response = await this.getDisabledResourceAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves Prometheus rule groups related to failures. Can be filtered for custom or all rules.
     * Get Prometheus failure rule groups
     */
    async getFailureRuleGroupsRaw(requestParameters: GetFailureRuleGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrometheusRuleGroupDto>> {
        const queryParameters: any = {};

        if (requestParameters['customFailureRules'] != null) {
            queryParameters['customFailureRules'] = requestParameters['customFailureRules'];
        }

        if (requestParameters['allFailureRuleGroups'] != null) {
            queryParameters['allFailureRuleGroups'] = requestParameters['allFailureRuleGroups'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/failure-rules`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves Prometheus rule groups related to failures. Can be filtered for custom or all rules.
     * Get Prometheus failure rule groups
     */
    async getFailureRuleGroups(requestParameters: GetFailureRuleGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrometheusRuleGroupDto> {
        const response = await this.getFailureRuleGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves alert configurations related to system health.
     * Get health-based alert configurations
     */
    async getHealthAlertConfigsRaw(requestParameters: GetHealthAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves alert configurations related to system health.
     * Get health-based alert configurations
     */
    async getHealthAlertConfigs(requestParameters: GetHealthAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertConfigsDto> {
        const response = await this.getHealthAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves alert configurations specifically for requests.
     * Get request-based alert configurations
     */
    async getRequestAlertConfigsRaw(requestParameters: GetRequestAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts/request`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves alert configurations specifically for requests.
     * Get request-based alert configurations
     */
    async getRequestAlertConfigs(requestParameters: GetRequestAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertConfigsDto> {
        const response = await this.getRequestAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves alert configurations specifically for resources.
     * Get resource-based alert configurations
     */
    async getResourceAlertConfigsRaw(requestParameters: GetResourceAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts/resource`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves alert configurations specifically for resources.
     * Get resource-based alert configurations
     */
    async getResourceAlertConfigs(requestParameters: GetResourceAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertConfigsDto> {
        const response = await this.getResourceAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves alert configurations related to Service Level Objectives.
     * Get SLO-based alert configurations
     */
    async getSloAlertConfigsRaw(requestParameters: GetSloAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertConfigsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts/slo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves alert configurations related to Service Level Objectives.
     * Get SLO-based alert configurations
     */
    async getSloAlertConfigs(requestParameters: GetSloAlertConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertConfigsDto> {
        const response = await this.getSloAlertConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new alert configuration or updates an existing one based on the provided data.
     * Create or update a single alert configuration
     */
    async putAlertConfigRaw(requestParameters: PutAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['alertConfigDto'] == null) {
            throw new runtime.RequiredError(
                'alertConfigDto',
                'Required parameter "alertConfigDto" was null or undefined when calling putAlertConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alert`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['alertConfigDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new alert configuration or updates an existing one based on the provided data.
     * Create or update a single alert configuration
     */
    async putAlertConfig(requestParameters: PutAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putAlertConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Creates or updates a batch of alert configurations.
     * Create or update multiple alert configurations
     */
    async putAlertConfigsRaw(requestParameters: PutAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['alertConfigsDto'] == null) {
            throw new runtime.RequiredError(
                'alertConfigsDto',
                'Required parameter "alertConfigsDto" was null or undefined when calling putAlertConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['alertConfigsDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates or updates a batch of alert configurations.
     * Create or update multiple alert configurations
     */
    async putAlertConfigs(requestParameters: PutAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putAlertConfigsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates a new disabled alert configuration, effectively silencing it.
     * Disable a single alert configuration
     */
    async putDisabledAlertConfigRaw(requestParameters: PutDisabledAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['disabledAlertConfigDto'] == null) {
            throw new runtime.RequiredError(
                'disabledAlertConfigDto',
                'Required parameter "disabledAlertConfigDto" was null or undefined when calling putDisabledAlertConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alert`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['disabledAlertConfigDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new disabled alert configuration, effectively silencing it.
     * Disable a single alert configuration
     */
    async putDisabledAlertConfig(requestParameters: PutDisabledAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putDisabledAlertConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Creates or updates a batch of disabled alert configurations.
     * Disable multiple alert configurations
     */
    async putDisabledAlertConfigsRaw(requestParameters: PutDisabledAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['disabledAlertConfigsDto'] == null) {
            throw new runtime.RequiredError(
                'disabledAlertConfigsDto',
                'Required parameter "disabledAlertConfigsDto" was null or undefined when calling putDisabledAlertConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alerts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['disabledAlertConfigsDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates or updates a batch of disabled alert configurations.
     * Disable multiple alert configurations
     */
    async putDisabledAlertConfigs(requestParameters: PutDisabledAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putDisabledAlertConfigsRaw(requestParameters, initOverrides);
    }

    /**
     * Validates a single alert configuration without persisting it. Returns 200 if valid, 422 with error details if invalid.
     * Validate a single alert configuration
     */
    async validateAlertConfigRaw(requestParameters: ValidateAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['alertConfigDto'] == null) {
            throw new runtime.RequiredError(
                'alertConfigDto',
                'Required parameter "alertConfigDto" was null or undefined when calling validateAlertConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alert-validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['alertConfigDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Validates a single alert configuration without persisting it. Returns 200 if valid, 422 with error details if invalid.
     * Validate a single alert configuration
     */
    async validateAlertConfig(requestParameters: ValidateAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.validateAlertConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Validates a batch of alert configurations without persisting them. Returns 200 if valid, 422 with error details if invalid.
     * Validate multiple alert configurations
     */
    async validateAlertConfigsRaw(requestParameters: ValidateAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['alertConfigsDto'] == null) {
            throw new runtime.RequiredError(
                'alertConfigsDto',
                'Required parameter "alertConfigsDto" was null or undefined when calling validateAlertConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/alerts-validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['alertConfigsDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Validates a batch of alert configurations without persisting them. Returns 200 if valid, 422 with error details if invalid.
     * Validate multiple alert configurations
     */
    async validateAlertConfigs(requestParameters: ValidateAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.validateAlertConfigsRaw(requestParameters, initOverrides);
    }

    /**
     * Validates a single disabled alert configuration without persisting it. Returns 200 if valid, 422 with error details if invalid.
     * Validate a single disabled alert configuration
     */
    async validateDisabledAlertConfigRaw(requestParameters: ValidateDisabledAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['disabledAlertConfigDto'] == null) {
            throw new runtime.RequiredError(
                'disabledAlertConfigDto',
                'Required parameter "disabledAlertConfigDto" was null or undefined when calling validateDisabledAlertConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alert-validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['disabledAlertConfigDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Validates a single disabled alert configuration without persisting it. Returns 200 if valid, 422 with error details if invalid.
     * Validate a single disabled alert configuration
     */
    async validateDisabledAlertConfig(requestParameters: ValidateDisabledAlertConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.validateDisabledAlertConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Validates a batch of disabled alert configurations without persisting them. Returns 200 if valid, 422 with error details if invalid.
     * Validate disabled alert configurations
     */
    async validateDisabledAlertConfigsRaw(requestParameters: ValidateDisabledAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['disabledAlertConfigsDto'] == null) {
            throw new runtime.RequiredError(
                'disabledAlertConfigsDto',
                'Required parameter "disabledAlertConfigsDto" was null or undefined when calling validateDisabledAlertConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/disabled-alerts-validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['disabledAlertConfigsDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Validates a batch of disabled alert configurations without persisting them. Returns 200 if valid, 422 with error details if invalid.
     * Validate disabled alert configurations
     */
    async validateDisabledAlertConfigs(requestParameters: ValidateDisabledAlertConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.validateDisabledAlertConfigsRaw(requestParameters, initOverrides);
    }

}
