/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssertionScoreRequestDto,
  AssertionScoresDto,
  AssertionSearchRequestDto,
  EntityKeyDto,
} from '../models/index';

export interface GetAssertionScoresRequest {
    assertionScoreRequestDto: AssertionScoreRequestDto;
    xScopeOrgID?: string;
}

export interface GetAssertionScoresFromSearchRequest {
    assertionSearchRequestDto: AssertionSearchRequestDto;
    xScopeOrgID?: string;
}

export interface GetTopNAssertingEntitiesRequest {
    assertionScoreRequestDto: AssertionScoreRequestDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class AssertionScoreControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAssertionScoresRaw(requestParameters: GetAssertionScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssertionScoresDto>> {
        if (requestParameters['assertionScoreRequestDto'] == null) {
            throw new runtime.RequiredError(
                'assertionScoreRequestDto',
                'Required parameter "assertionScoreRequestDto" was null or undefined when calling getAssertionScores().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/assertion_scores`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['assertionScoreRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getAssertionScores(requestParameters: GetAssertionScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssertionScoresDto> {
        const response = await this.getAssertionScoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAssertionScoresFromSearchRaw(requestParameters: GetAssertionScoresFromSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssertionScoresDto>> {
        if (requestParameters['assertionSearchRequestDto'] == null) {
            throw new runtime.RequiredError(
                'assertionSearchRequestDto',
                'Required parameter "assertionSearchRequestDto" was null or undefined when calling getAssertionScoresFromSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/assertion_scores/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['assertionSearchRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getAssertionScoresFromSearch(requestParameters: GetAssertionScoresFromSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssertionScoresDto> {
        const response = await this.getAssertionScoresFromSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getTopNAssertingEntitiesRaw(requestParameters: GetTopNAssertingEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EntityKeyDto>>> {
        if (requestParameters['assertionScoreRequestDto'] == null) {
            throw new runtime.RequiredError(
                'assertionScoreRequestDto',
                'Required parameter "assertionScoreRequestDto" was null or undefined when calling getTopNAssertingEntities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/assertion_scores/top_entities`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['assertionScoreRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getTopNAssertingEntities(requestParameters: GetTopNAssertingEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EntityKeyDto>> {
        const response = await this.getTopNAssertingEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
