/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssertionSearchRequestDto,
  EntityKeyDto,
} from '../models/index';

export interface Search3Request {
    assertionSearchRequestDto: AssertionSearchRequestDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class AssertionSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async search3Raw(requestParameters: Search3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EntityKeyDto>>> {
        if (requestParameters['assertionSearchRequestDto'] == null) {
            throw new runtime.RequiredError(
                'assertionSearchRequestDto',
                'Required parameter "assertionSearchRequestDto" was null or undefined when calling search3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/assertions/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['assertionSearchRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async search3(requestParameters: Search3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EntityKeyDto>> {
        const response = await this.search3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
