/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RetainedLabelConfig,
} from '../models/index';

export interface DeleteConfigRequest {
    xScopeOrgID?: string;
}

export interface GetConfigRequest {
    xScopeOrgID?: string;
}

export interface PutConfigRequest {
    retainedLabelConfig: RetainedLabelConfig;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class CustomLabelRetentionApi extends runtime.BaseAPI {

    /**
     * Delete retained label config for the current tenant
     */
    async deleteConfigRaw(requestParameters: DeleteConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/custom-labels`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete retained label config for the current tenant
     */
    async deleteConfig(requestParameters: DeleteConfigRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConfigRaw(requestParameters, initOverrides);
    }

    /**
     * Get retained label config for the current tenant
     */
    async getConfigRaw(requestParameters: GetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetainedLabelConfig>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/custom-labels`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get retained label config for the current tenant
     */
    async getConfig(requestParameters: GetConfigRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetainedLabelConfig> {
        const response = await this.getConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or update retained label config for the current tenant
     */
    async putConfigRaw(requestParameters: PutConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['retainedLabelConfig'] == null) {
            throw new runtime.RequiredError(
                'retainedLabelConfig',
                'Required parameter "retainedLabelConfig" was null or undefined when calling putConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/custom-labels`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['retainedLabelConfig'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create or update retained label config for the current tenant
     */
    async putConfig(requestParameters: PutConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putConfigRaw(requestParameters, initOverrides);
    }

}
