/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PatternDto,
} from '../models/index';

export interface DeleteCustomRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface GetCustomByNameRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface ListCustomRequest {
    xScopeOrgID?: string;
}

export interface PutCustomRequest {
    patternDto: PatternDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class CustomRcaPatternControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteCustomRaw(requestParameters: DeleteCustomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteCustom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/patterns/custom/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteCustom(requestParameters: DeleteCustomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCustomRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getCustomByNameRaw(requestParameters: GetCustomByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PatternDto>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getCustomByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/patterns/custom/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getCustomByName(requestParameters: GetCustomByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PatternDto> {
        const response = await this.getCustomByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listCustomRaw(requestParameters: ListCustomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PatternDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/patterns/custom`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async listCustom(requestParameters: ListCustomRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PatternDto>> {
        const response = await this.listCustomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putCustomRaw(requestParameters: PutCustomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['patternDto'] == null) {
            throw new runtime.RequiredError(
                'patternDto',
                'Required parameter "patternDto" was null or undefined when calling putCustom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/patterns/custom`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['patternDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async putCustom(requestParameters: PutCustomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putCustomRaw(requestParameters, initOverrides);
    }

}
