/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CypherSearchRequestDto,
  CypherSearchResponseDto,
} from '../models/index';

export interface Search1Request {
    cypherSearchRequestDto: CypherSearchRequestDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class CypherSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async search1Raw(requestParameters: Search1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CypherSearchResponseDto>> {
        if (requestParameters['cypherSearchRequestDto'] == null) {
            throw new runtime.RequiredError(
                'cypherSearchRequestDto',
                'Required parameter "cypherSearchRequestDto" was null or undefined when calling search1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/search/cypher`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['cypherSearchRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async search1(requestParameters: Search1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CypherSearchResponseDto> {
        const response = await this.search1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
