/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DrilldownConfigMigrationDto,
} from '../models/index';

export interface MigrateConfigsRequest {
    drilldownConfigMigrationDto: DrilldownConfigMigrationDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class DrilldownConfigMigrationControllerApi extends runtime.BaseAPI {

    /**
     */
    async migrateConfigsRaw(requestParameters: MigrateConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['drilldownConfigMigrationDto'] == null) {
            throw new runtime.RequiredError(
                'drilldownConfigMigrationDto',
                'Required parameter "drilldownConfigMigrationDto" was null or undefined when calling migrateConfigs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/drilldown-migration`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['drilldownConfigMigrationDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async migrateConfigs(requestParameters: MigrateConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.migrateConfigsRaw(requestParameters, initOverrides);
    }

}
