/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GraphEntityKpiValue,
  KpiListDto,
  KpiSummaryRequestDto,
} from '../models/index';

export interface GetKpiSummaryRequest {
    kpiName: string;
    kpiSummaryRequestDto: KpiSummaryRequestDto;
    xScopeOrgID?: string;
}

export interface GetKpisByEntityTypeRequest {
    xScopeOrgID?: string;
}

/**
 * 
 */
export class EntityKpiControllerApi extends runtime.BaseAPI {

    /**
     */
    async getKpiSummaryRaw(requestParameters: GetKpiSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: GraphEntityKpiValue; }>> {
        if (requestParameters['kpiName'] == null) {
            throw new runtime.RequiredError(
                'kpiName',
                'Required parameter "kpiName" was null or undefined when calling getKpiSummary().'
            );
        }

        if (requestParameters['kpiSummaryRequestDto'] == null) {
            throw new runtime.RequiredError(
                'kpiSummaryRequestDto',
                'Required parameter "kpiSummaryRequestDto" was null or undefined when calling getKpiSummary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/kpi/summary/for-entities/{kpi_name}`.replace(`{${"kpi_name"}}`, encodeURIComponent(String(requestParameters['kpiName']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['kpiSummaryRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getKpiSummary(requestParameters: GetKpiSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: GraphEntityKpiValue; }> {
        const response = await this.getKpiSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getKpisByEntityTypeRaw(requestParameters: GetKpisByEntityTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KpiListDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/kpi/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getKpisByEntityType(requestParameters: GetKpisByEntityTypeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KpiListDto> {
        const response = await this.getKpisByEntityTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
