/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GraphEntity,
} from '../models/index';

export interface GetEntityRequest {
    entityType: string;
    entityName: string;
    env?: string;
    site?: string;
    namespace?: string;
    domain?: string;
    start?: number;
    end?: number;
    xScopeOrgID?: string;
}

export interface LookupEntityFromAlertLabelsRequest {
    requestParams: { [key: string]: string; };
    env?: string;
    site?: string;
    namespace?: string;
    domain?: string;
    start?: number;
    end?: number;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class EntityControllerApi extends runtime.BaseAPI {

    /**
     */
    async getEntityRaw(requestParameters: GetEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphEntity>> {
        if (requestParameters['entityType'] == null) {
            throw new runtime.RequiredError(
                'entityType',
                'Required parameter "entityType" was null or undefined when calling getEntity().'
            );
        }

        if (requestParameters['entityName'] == null) {
            throw new runtime.RequiredError(
                'entityName',
                'Required parameter "entityName" was null or undefined when calling getEntity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['entityType'] != null) {
            queryParameters['entity_type'] = requestParameters['entityType'];
        }

        if (requestParameters['entityName'] != null) {
            queryParameters['entity_name'] = requestParameters['entityName'];
        }

        if (requestParameters['env'] != null) {
            queryParameters['env'] = requestParameters['env'];
        }

        if (requestParameters['site'] != null) {
            queryParameters['site'] = requestParameters['site'];
        }

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        if (requestParameters['domain'] != null) {
            queryParameters['domain'] = requestParameters['domain'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/entity/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getEntity(requestParameters: GetEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphEntity> {
        const response = await this.getEntityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async lookupEntityFromAlertLabelsRaw(requestParameters: LookupEntityFromAlertLabelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphEntity>> {
        if (requestParameters['requestParams'] == null) {
            throw new runtime.RequiredError(
                'requestParams',
                'Required parameter "requestParams" was null or undefined when calling lookupEntityFromAlertLabels().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['env'] != null) {
            queryParameters['env'] = requestParameters['env'];
        }

        if (requestParameters['site'] != null) {
            queryParameters['site'] = requestParameters['site'];
        }

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        if (requestParameters['domain'] != null) {
            queryParameters['domain'] = requestParameters['domain'];
        }

        if (requestParameters['requestParams'] != null) {
            queryParameters['requestParams'] = requestParameters['requestParams'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/entity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async lookupEntityFromAlertLabels(requestParameters: LookupEntityFromAlertLabelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphEntity> {
        const response = await this.lookupEntityFromAlertLabelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
