/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityScopesRequestDto,
  EntityScopesResponseDto,
  EntityScopesV2ResponseDto,
} from '../models/index';

export interface GetAllEntityScopesRequest {
    start?: number;
    end?: number;
    xScopeOrgID?: string;
}

export interface GetAllEntityScopesV2Request {
    start?: number;
    end?: number;
    xScopeOrgID?: string;
}

export interface GetEntityScopesRequest {
    entityScopesRequestDto: EntityScopesRequestDto;
    xScopeOrgID?: string;
}

export interface GetEntityScopesV2Request {
    entityScopesRequestDto: EntityScopesRequestDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class EntityScopeControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllEntityScopesRaw(requestParameters: GetAllEntityScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityScopesResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/entity_scope`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getAllEntityScopes(requestParameters: GetAllEntityScopesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityScopesResponseDto> {
        const response = await this.getAllEntityScopesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllEntityScopesV2Raw(requestParameters: GetAllEntityScopesV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityScopesV2ResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/entity_scope`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getAllEntityScopesV2(requestParameters: GetAllEntityScopesV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityScopesV2ResponseDto> {
        const response = await this.getAllEntityScopesV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEntityScopesRaw(requestParameters: GetEntityScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityScopesResponseDto>> {
        if (requestParameters['entityScopesRequestDto'] == null) {
            throw new runtime.RequiredError(
                'entityScopesRequestDto',
                'Required parameter "entityScopesRequestDto" was null or undefined when calling getEntityScopes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/entity_scope`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['entityScopesRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getEntityScopes(requestParameters: GetEntityScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityScopesResponseDto> {
        const response = await this.getEntityScopesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEntityScopesV2Raw(requestParameters: GetEntityScopesV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityScopesV2ResponseDto>> {
        if (requestParameters['entityScopesRequestDto'] == null) {
            throw new runtime.RequiredError(
                'entityScopesRequestDto',
                'Required parameter "entityScopesRequestDto" was null or undefined when calling getEntityScopesV2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/entity_scope`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['entityScopesRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getEntityScopesV2(requestParameters: GetEntityScopesV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityScopesV2ResponseDto> {
        const response = await this.getEntityScopesV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
