/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GraphDisplayConfigDto,
} from '../models/index';

export interface DeleteGraphEdgeDisplayConfigRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface DeleteGraphEntityDisplayConfigRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface GetGraphDisplayConfigRequest {
    xScopeOrgID?: string;
}

export interface PutGraphDisplayConfigRequest {
    graphDisplayConfigDto: GraphDisplayConfigDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class GraphDisplayConfigControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteGraphEdgeDisplayConfigRaw(requestParameters: DeleteGraphEdgeDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteGraphEdgeDisplayConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/display/graph/edge_type/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteGraphEdgeDisplayConfig(requestParameters: DeleteGraphEdgeDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGraphEdgeDisplayConfigRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteGraphEntityDisplayConfigRaw(requestParameters: DeleteGraphEntityDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteGraphEntityDisplayConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/display/graph/entity_type/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteGraphEntityDisplayConfig(requestParameters: DeleteGraphEntityDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGraphEntityDisplayConfigRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getGraphDisplayConfigRaw(requestParameters: GetGraphDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GraphDisplayConfigDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/display/graph`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getGraphDisplayConfig(requestParameters: GetGraphDisplayConfigRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GraphDisplayConfigDto> {
        const response = await this.getGraphDisplayConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putGraphDisplayConfigRaw(requestParameters: PutGraphDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['graphDisplayConfigDto'] == null) {
            throw new runtime.RequiredError(
                'graphDisplayConfigDto',
                'Required parameter "graphDisplayConfigDto" was null or undefined when calling putGraphDisplayConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/display/graph`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['graphDisplayConfigDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async putGraphDisplayConfig(requestParameters: PutGraphDisplayConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putGraphDisplayConfigRaw(requestParameters, initOverrides);
    }

}
