/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  KgSizingDto,
} from '../models/index';

export interface GetKgSizingRequest {
    xScopeOrgID?: string;
}

/**
 * 
 */
export class KgSizingConfigControllerApi extends runtime.BaseAPI {

    /**
     */
    async getKgSizingRaw(requestParameters: GetKgSizingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KgSizingDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/kg-sizing`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getKgSizing(requestParameters: GetKgSizingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KgSizingDto> {
        const response = await this.getKgSizingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
