/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityKeyDto,
  LatencyThresholdDto,
  LatencyThresholdsDto,
} from '../models/index';

export interface GetLatencyThresholdsRequest {
    entityKeyDto: Array<EntityKeyDto>;
    xScopeOrgID?: string;
}

export interface GetLatencyThresholds1Request {
    entityKeyDto: EntityKeyDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class LatencyThresholdControllerApi extends runtime.BaseAPI {

    /**
     */
    async getLatencyThresholdsRaw(requestParameters: GetLatencyThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LatencyThresholdsDto>>> {
        if (requestParameters['entityKeyDto'] == null) {
            throw new runtime.RequiredError(
                'entityKeyDto',
                'Required parameter "entityKeyDto" was null or undefined when calling getLatencyThresholds().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/latency-thresholds`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['entityKeyDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getLatencyThresholds(requestParameters: GetLatencyThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LatencyThresholdsDto>> {
        const response = await this.getLatencyThresholdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLatencyThresholds1Raw(requestParameters: GetLatencyThresholds1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LatencyThresholdDto>>> {
        if (requestParameters['entityKeyDto'] == null) {
            throw new runtime.RequiredError(
                'entityKeyDto',
                'Required parameter "entityKeyDto" was null or undefined when calling getLatencyThresholds1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/latency-thresholds`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['entityKeyDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getLatencyThresholds1(requestParameters: GetLatencyThresholds1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LatencyThresholdDto>> {
        const response = await this.getLatencyThresholds1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
