/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  TenantLogConfigResponseDto,
} from '../models/index';

export interface DeleteConfig4Request {
    name: string;
    xScopeOrgID?: string;
}

export interface GetTenantLogConfigRequest {
    xScopeOrgID?: string;
}

export interface ReorderLogConfigPrioritiesRequest {
    body: string;
    xScopeOrgID?: string;
}

export interface UpsertLogDrilldownConfigRequest {
    body: string;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class LogDrilldownConfigControllerApi extends runtime.BaseAPI {

    /**
     * Deletes the specified log drilldown configuration entry for the tenant
     * Delete log drilldown configuration
     */
    async deleteConfig4Raw(requestParameters: DeleteConfig4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteConfig4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/log/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the specified log drilldown configuration entry for the tenant
     * Delete log drilldown configuration
     */
    async deleteConfig4(requestParameters: DeleteConfig4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConfig4Raw(requestParameters, initOverrides);
    }

    /**
     * Retrieves all the log drilldown configuration entries for the tenant
     * Get tenant log configuration
     */
    async getTenantLogConfigRaw(requestParameters: GetTenantLogConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantLogConfigResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/log`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves all the log drilldown configuration entries for the tenant
     * Get tenant log configuration
     */
    async getTenantLogConfig(requestParameters: GetTenantLogConfigRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantLogConfigResponseDto> {
        const response = await this.getTenantLogConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a list of log drilldown configuration names and their new priorities to reorder the configurations for the tenant
     * Reorder log drilldown configuration priorities
     */
    async reorderLogConfigPrioritiesRaw(requestParameters: ReorderLogConfigPrioritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantLogConfigResponseDto>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling reorderLogConfigPriorities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/log/reorder`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Accepts a list of log drilldown configuration names and their new priorities to reorder the configurations for the tenant
     * Reorder log drilldown configuration priorities
     */
    async reorderLogConfigPriorities(requestParameters: ReorderLogConfigPrioritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantLogConfigResponseDto> {
        const response = await this.reorderLogConfigPrioritiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates or updates the log drilldown configuration entry for the tenant
     * Upsert log drilldown configuration
     */
    async upsertLogDrilldownConfigRaw(requestParameters: UpsertLogDrilldownConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling upsertLogDrilldownConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates or updates the log drilldown configuration entry for the tenant
     * Upsert log drilldown configuration
     */
    async upsertLogDrilldownConfig(requestParameters: UpsertLogDrilldownConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.upsertLogDrilldownConfigRaw(requestParameters, initOverrides);
    }

}
