/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MimirRelabelRuleGroupDto,
} from '../models/index';

export interface DeleteEpilogueRelabelRulesRequest {
    xScopeOrgID?: string;
}

export interface DeletePrologueRelabelRulesRequest {
    xScopeOrgID?: string;
}

export interface GetEpilogueRelabelRulesRequest {
    xScopeOrgID?: string;
}

export interface GetGeneratedRelabelRulesRequest {
    xScopeOrgID?: string;
}

export interface GetPrologueRelabelRulesRequest {
    xScopeOrgID?: string;
}

export interface PutMimirEpilogueRelabelRulesRequest {
    mimirRelabelRuleGroupDto: MimirRelabelRuleGroupDto;
    xScopeOrgID?: string;
}

export interface PutMimirPrologueRelabelRulesRequest {
    mimirRelabelRuleGroupDto: MimirRelabelRuleGroupDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class MimirRelabelRulesConfigControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteEpilogueRelabelRulesRaw(requestParameters: DeleteEpilogueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/epilogue`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteEpilogueRelabelRules(requestParameters: DeleteEpilogueRelabelRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEpilogueRelabelRulesRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deletePrologueRelabelRulesRaw(requestParameters: DeletePrologueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/prologue`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deletePrologueRelabelRules(requestParameters: DeletePrologueRelabelRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePrologueRelabelRulesRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getEpilogueRelabelRulesRaw(requestParameters: GetEpilogueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MimirRelabelRuleGroupDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/epilogue`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getEpilogueRelabelRules(requestParameters: GetEpilogueRelabelRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MimirRelabelRuleGroupDto> {
        const response = await this.getEpilogueRelabelRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGeneratedRelabelRulesRaw(requestParameters: GetGeneratedRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MimirRelabelRuleGroupDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/generated`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getGeneratedRelabelRules(requestParameters: GetGeneratedRelabelRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MimirRelabelRuleGroupDto> {
        const response = await this.getGeneratedRelabelRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPrologueRelabelRulesRaw(requestParameters: GetPrologueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MimirRelabelRuleGroupDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/prologue`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getPrologueRelabelRules(requestParameters: GetPrologueRelabelRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MimirRelabelRuleGroupDto> {
        const response = await this.getPrologueRelabelRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putMimirEpilogueRelabelRulesRaw(requestParameters: PutMimirEpilogueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mimirRelabelRuleGroupDto'] == null) {
            throw new runtime.RequiredError(
                'mimirRelabelRuleGroupDto',
                'Required parameter "mimirRelabelRuleGroupDto" was null or undefined when calling putMimirEpilogueRelabelRules().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/epilogue`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['mimirRelabelRuleGroupDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async putMimirEpilogueRelabelRules(requestParameters: PutMimirEpilogueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putMimirEpilogueRelabelRulesRaw(requestParameters, initOverrides);
    }

    /**
     */
    async putMimirPrologueRelabelRulesRaw(requestParameters: PutMimirPrologueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mimirRelabelRuleGroupDto'] == null) {
            throw new runtime.RequiredError(
                'mimirRelabelRuleGroupDto',
                'Required parameter "mimirRelabelRuleGroupDto" was null or undefined when calling putMimirPrologueRelabelRules().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/relabel-rules/prologue`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['mimirRelabelRuleGroupDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async putMimirPrologueRelabelRules(requestParameters: PutMimirPrologueRelabelRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putMimirPrologueRelabelRulesRaw(requestParameters, initOverrides);
    }

}
