/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  TenantProfileConfigResponseDto,
} from '../models/index';

export interface DeleteConfig2Request {
    name: string;
    xScopeOrgID?: string;
}

export interface GetTenantProfileConfigRequest {
    xScopeOrgID?: string;
}

export interface ReorderProfileConfigPrioritiesRequest {
    body: string;
    xScopeOrgID?: string;
}

export interface UpsertProfileDrilldownConfigRequest {
    body: string;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class ProfileDrilldownConfigControllerApi extends runtime.BaseAPI {

    /**
     * Deletes the specified profile drilldown configuration entry for the tenant
     * Delete profile drilldown configuration
     */
    async deleteConfig2Raw(requestParameters: DeleteConfig2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteConfig2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/profile/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the specified profile drilldown configuration entry for the tenant
     * Delete profile drilldown configuration
     */
    async deleteConfig2(requestParameters: DeleteConfig2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConfig2Raw(requestParameters, initOverrides);
    }

    /**
     * Retrieves all the profile drilldown configuration entries for the tenant
     * Get tenant profile configuration
     */
    async getTenantProfileConfigRaw(requestParameters: GetTenantProfileConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantProfileConfigResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves all the profile drilldown configuration entries for the tenant
     * Get tenant profile configuration
     */
    async getTenantProfileConfig(requestParameters: GetTenantProfileConfigRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantProfileConfigResponseDto> {
        const response = await this.getTenantProfileConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a list of profile drilldown configuration names and their new priorities to reorder the configurations for the tenant
     * Reorder profile drilldown configuration priorities
     */
    async reorderProfileConfigPrioritiesRaw(requestParameters: ReorderProfileConfigPrioritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantProfileConfigResponseDto>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling reorderProfileConfigPriorities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/profile/reorder`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Accepts a list of profile drilldown configuration names and their new priorities to reorder the configurations for the tenant
     * Reorder profile drilldown configuration priorities
     */
    async reorderProfileConfigPriorities(requestParameters: ReorderProfileConfigPrioritiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantProfileConfigResponseDto> {
        const response = await this.reorderProfileConfigPrioritiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates or updates the profile drilldown configuration entry for the tenant
     * Upsert profile drilldown configuration
     */
    async upsertProfileDrilldownConfigRaw(requestParameters: UpsertProfileDrilldownConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling upsertProfileDrilldownConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/profile`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates or updates the profile drilldown configuration entry for the tenant
     * Upsert profile drilldown configuration
     */
    async upsertProfileDrilldownConfig(requestParameters: UpsertProfileDrilldownConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.upsertProfileDrilldownConfigRaw(requestParameters, initOverrides);
    }

}
