/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RcaPatternListRequestDto,
  RcaPatternSearchRequestDto,
  RcaPatternSearchResponseDto,
} from '../models/index';

export interface ListRequest {
    rcaPatternListRequestDto: RcaPatternListRequestDto;
    xScopeOrgID?: string;
}

export interface Search2Request {
    rcaPatternSearchRequestDto: RcaPatternSearchRequestDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class RcaPatternControllerApi extends runtime.BaseAPI {

    /**
     */
    async listRaw(requestParameters: ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['rcaPatternListRequestDto'] == null) {
            throw new runtime.RequiredError(
                'rcaPatternListRequestDto',
                'Required parameter "rcaPatternListRequestDto" was null or undefined when calling list().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/patterns/list`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['rcaPatternListRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async list(requestParameters: ListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async search2Raw(requestParameters: Search2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RcaPatternSearchResponseDto>> {
        if (requestParameters['rcaPatternSearchRequestDto'] == null) {
            throw new runtime.RequiredError(
                'rcaPatternSearchRequestDto',
                'Required parameter "rcaPatternSearchRequestDto" was null or undefined when calling search2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/patterns/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['rcaPatternSearchRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async search2(requestParameters: Search2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RcaPatternSearchResponseDto> {
        const response = await this.search2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
