/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AllRulesDto,
} from '../models/index';

export interface GetAllRulesRequest {
    xScopeOrgID?: string;
}

/**
 * 
 */
export class RulesControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllRulesRaw(requestParameters: GetAllRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllRulesDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v5/prometheus/rules`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getAllRules(requestParameters: GetAllRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllRulesDto> {
        const response = await this.getAllRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
