/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SampleSearchRequestDto,
  SampleSearchResponseDto,
} from '../models/index';

export interface SearchSampleRequest {
    sampleSearchRequestDto: SampleSearchRequestDto;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class SampleSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async searchSampleRaw(requestParameters: SearchSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SampleSearchResponseDto>> {
        if (requestParameters['sampleSearchRequestDto'] == null) {
            throw new runtime.RequiredError(
                'sampleSearchRequestDto',
                'Required parameter "sampleSearchRequestDto" was null or undefined when calling searchSample().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/search/sample`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sampleSearchRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async searchSample(requestParameters: SearchSampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SampleSearchResponseDto> {
        const response = await this.searchSampleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
