/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfigValidationResponseDto,
  SloConfigRequestDto,
  SloConfigResponseDto,
} from '../models/index';

export interface DeleteSloConfigRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface GetSloConfigRequest {
    name: string;
    xScopeOrgID?: string;
}

export interface GetSloConfigsRequest {
    xScopeOrgID?: string;
}

export interface PostSloConfigRequest {
    sloConfigRequestDto: SloConfigRequestDto;
    xScopeOrgID?: string;
}

export interface RegenerateSloRulesRequest {
    xScopeOrgID?: string;
}

export interface ValidateRequest {
    sloConfigRequestDto: SloConfigRequestDto;
    start?: number;
    end?: number;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class SloConfigControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteSloConfigRaw(requestParameters: DeleteSloConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteSloConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/slo/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteSloConfig(requestParameters: DeleteSloConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSloConfigRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getSloConfigRaw(requestParameters: GetSloConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SloConfigResponseDto>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getSloConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/slo/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getSloConfig(requestParameters: GetSloConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SloConfigResponseDto> {
        const response = await this.getSloConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSloConfigsRaw(requestParameters: GetSloConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SloConfigResponseDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/slo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getSloConfigs(requestParameters: GetSloConfigsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SloConfigResponseDto>> {
        const response = await this.getSloConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postSloConfigRaw(requestParameters: PostSloConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sloConfigRequestDto'] == null) {
            throw new runtime.RequiredError(
                'sloConfigRequestDto',
                'Required parameter "sloConfigRequestDto" was null or undefined when calling postSloConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/slo`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sloConfigRequestDto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async postSloConfig(requestParameters: PostSloConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postSloConfigRaw(requestParameters, initOverrides);
    }

    /**
     */
    async regenerateSloRulesRaw(requestParameters: RegenerateSloRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/slo-generate-rules`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async regenerateSloRules(requestParameters: RegenerateSloRulesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.regenerateSloRulesRaw(requestParameters, initOverrides);
    }

    /**
     */
    async validateRaw(requestParameters: ValidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigValidationResponseDto>> {
        if (requestParameters['sloConfigRequestDto'] == null) {
            throw new runtime.RequiredError(
                'sloConfigRequestDto',
                'Required parameter "sloConfigRequestDto" was null or undefined when calling validate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v1/config/slo-validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sloConfigRequestDto'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async validate(requestParameters: ValidateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigValidationResponseDto> {
        const response = await this.validateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
