/* tslint:disable */
/* eslint-disable */
/**
 * Asserts, Inc
 * Asserts Public API
 *
 * The version of the OpenAPI document: 2026.09.09-102835
 * Contact: support@asserts.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthThresholdV2Dto,
  RequestThresholdV2Dto,
  ResourceThresholdV2Dto,
  ThresholdsV2Dto,
} from '../models/index';

export interface DeleteThresholdsRequest {
    xScopeOrgID?: string;
    thresholdsV2Dto?: ThresholdsV2Dto;
}

export interface GetThresholdsRequest {
    xScopeOrgID?: string;
}

export interface UpdateAllThresholdsRequest {
    thresholdsV2Dto: ThresholdsV2Dto;
    xScopeOrgID?: string;
}

export interface UpdateHealthThresholdsRequest {
    healthThresholdV2Dto: Array<HealthThresholdV2Dto>;
    xScopeOrgID?: string;
}

export interface UpdateRequestThresholdsRequest {
    requestThresholdV2Dto: Array<RequestThresholdV2Dto>;
    xScopeOrgID?: string;
}

export interface UpdateResourceThresholdsRequest {
    resourceThresholdV2Dto: Array<ResourceThresholdV2Dto>;
    xScopeOrgID?: string;
}

/**
 * 
 */
export class ThresholdsV2ConfigControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteThresholdsRaw(requestParameters: DeleteThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/threshold`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['thresholdsV2Dto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteThresholds(requestParameters: DeleteThresholdsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteThresholdsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getThresholdsRaw(requestParameters: GetThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThresholdsV2Dto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/threshold`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async getThresholds(requestParameters: GetThresholdsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThresholdsV2Dto> {
        const response = await this.getThresholdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateAllThresholdsRaw(requestParameters: UpdateAllThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['thresholdsV2Dto'] == null) {
            throw new runtime.RequiredError(
                'thresholdsV2Dto',
                'Required parameter "thresholdsV2Dto" was null or undefined when calling updateAllThresholds().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/threshold`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['thresholdsV2Dto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateAllThresholds(requestParameters: UpdateAllThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateAllThresholdsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateHealthThresholdsRaw(requestParameters: UpdateHealthThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['healthThresholdV2Dto'] == null) {
            throw new runtime.RequiredError(
                'healthThresholdV2Dto',
                'Required parameter "healthThresholdV2Dto" was null or undefined when calling updateHealthThresholds().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/threshold/health`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['healthThresholdV2Dto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateHealthThresholds(requestParameters: UpdateHealthThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateHealthThresholdsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateRequestThresholdsRaw(requestParameters: UpdateRequestThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['requestThresholdV2Dto'] == null) {
            throw new runtime.RequiredError(
                'requestThresholdV2Dto',
                'Required parameter "requestThresholdV2Dto" was null or undefined when calling updateRequestThresholds().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/threshold/request`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestThresholdV2Dto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateRequestThresholds(requestParameters: UpdateRequestThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateRequestThresholdsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateResourceThresholdsRaw(requestParameters: UpdateResourceThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['resourceThresholdV2Dto'] == null) {
            throw new runtime.RequiredError(
                'resourceThresholdV2Dto',
                'Required parameter "resourceThresholdV2Dto" was null or undefined when calling updateResourceThresholds().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xScopeOrgID'] != null) {
            headerParameters['X-Scope-OrgID'] = String(requestParameters['xScopeOrgID']);
        }

        const response = await this.request({
            path: `/asserts/api-server/v2/config/threshold/resource`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['resourceThresholdV2Dto'],
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateResourceThresholds(requestParameters: UpdateResourceThresholdsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateResourceThresholdsRaw(requestParameters, initOverrides);
    }

}
