/*
Asserts, Inc

Asserts Public API

API version: 0.0.0
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kgwrite

import (
	"encoding/json"
)

// checks if the RelationshipWriteRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipWriteRequestDto{}

// RelationshipWriteRequestDto struct for RelationshipWriteRequestDto
type RelationshipWriteRequestDto struct {
	Domain               string            `json:"domain" validate:"regexp=^(?!kg$)[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$"`
	Type                 string            `json:"type" validate:"regexp=^[A-Za-z][A-Za-z0-9_]*$"`
	From                 EntityRefDto      `json:"from"`
	To                   EntityRefDto      `json:"to"`
	Properties           map[string]string `json:"properties,omitempty"`
	TtlSeconds           int64             `json:"ttlSeconds"`
	AdditionalProperties map[string]interface{}
}

type _RelationshipWriteRequestDto RelationshipWriteRequestDto

// NewRelationshipWriteRequestDto instantiates a new RelationshipWriteRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipWriteRequestDto(domain string, type_ string, from EntityRefDto, to EntityRefDto, ttlSeconds int64) *RelationshipWriteRequestDto {
	this := RelationshipWriteRequestDto{}
	this.Domain = domain
	this.Type = type_
	this.From = from
	this.To = to
	this.TtlSeconds = ttlSeconds
	return &this
}

// NewRelationshipWriteRequestDtoWithDefaults instantiates a new RelationshipWriteRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipWriteRequestDtoWithDefaults() *RelationshipWriteRequestDto {
	this := RelationshipWriteRequestDto{}
	return &this
}

// GetDomain returns the Domain field value
func (o *RelationshipWriteRequestDto) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *RelationshipWriteRequestDto) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *RelationshipWriteRequestDto) SetDomain(v string) {
	o.Domain = v
}

// GetType returns the Type field value
func (o *RelationshipWriteRequestDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RelationshipWriteRequestDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RelationshipWriteRequestDto) SetType(v string) {
	o.Type = v
}

// GetFrom returns the From field value
func (o *RelationshipWriteRequestDto) GetFrom() EntityRefDto {
	if o == nil {
		var ret EntityRefDto
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *RelationshipWriteRequestDto) GetFromOk() (*EntityRefDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *RelationshipWriteRequestDto) SetFrom(v EntityRefDto) {
	o.From = v
}

// GetTo returns the To field value
func (o *RelationshipWriteRequestDto) GetTo() EntityRefDto {
	if o == nil {
		var ret EntityRefDto
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *RelationshipWriteRequestDto) GetToOk() (*EntityRefDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *RelationshipWriteRequestDto) SetTo(v EntityRefDto) {
	o.To = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *RelationshipWriteRequestDto) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationshipWriteRequestDto) GetPropertiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]string{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *RelationshipWriteRequestDto) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *RelationshipWriteRequestDto) SetProperties(v map[string]string) {
	o.Properties = v
}

// GetTtlSeconds returns the TtlSeconds field value
func (o *RelationshipWriteRequestDto) GetTtlSeconds() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TtlSeconds
}

// GetTtlSecondsOk returns a tuple with the TtlSeconds field value
// and a boolean to check if the value has been set.
func (o *RelationshipWriteRequestDto) GetTtlSecondsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TtlSeconds, true
}

// SetTtlSeconds sets field value
func (o *RelationshipWriteRequestDto) SetTtlSeconds(v int64) {
	o.TtlSeconds = v
}

func (o RelationshipWriteRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipWriteRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["type"] = o.Type
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	toSerialize["ttlSeconds"] = o.TtlSeconds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RelationshipWriteRequestDto) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varRelationshipWriteRequestDto := _RelationshipWriteRequestDto{}

	err = json.Unmarshal(data, &varRelationshipWriteRequestDto)

	if err != nil {
		return err
	}

	*o = RelationshipWriteRequestDto(varRelationshipWriteRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		delete(additionalProperties, "type")
		delete(additionalProperties, "from")
		delete(additionalProperties, "to")
		delete(additionalProperties, "properties")
		delete(additionalProperties, "ttlSeconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRelationshipWriteRequestDto struct {
	value *RelationshipWriteRequestDto
	isSet bool
}

func (v NullableRelationshipWriteRequestDto) Get() *RelationshipWriteRequestDto {
	return v.value
}

func (v *NullableRelationshipWriteRequestDto) Set(val *RelationshipWriteRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipWriteRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipWriteRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipWriteRequestDto(val *RelationshipWriteRequestDto) *NullableRelationshipWriteRequestDto {
	return &NullableRelationshipWriteRequestDto{value: val, isSet: true}
}

func (v NullableRelationshipWriteRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipWriteRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
