/*
Asserts, Inc

Asserts Public API

API version: 0.0.0
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kgwrite

import (
	"encoding/json"
)

// checks if the EntityWriteResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityWriteResponseDto{}

// EntityWriteResponseDto struct for EntityWriteResponseDto
type EntityWriteResponseDto struct {
	Domain               *string                `json:"domain,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Scope                map[string]string      `json:"scope,omitempty"`
	Properties           map[string]interface{} `json:"properties,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EntityWriteResponseDto EntityWriteResponseDto

// NewEntityWriteResponseDto instantiates a new EntityWriteResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityWriteResponseDto() *EntityWriteResponseDto {
	this := EntityWriteResponseDto{}
	return &this
}

// NewEntityWriteResponseDtoWithDefaults instantiates a new EntityWriteResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityWriteResponseDtoWithDefaults() *EntityWriteResponseDto {
	this := EntityWriteResponseDto{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *EntityWriteResponseDto) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityWriteResponseDto) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *EntityWriteResponseDto) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *EntityWriteResponseDto) SetDomain(v string) {
	o.Domain = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EntityWriteResponseDto) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityWriteResponseDto) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EntityWriteResponseDto) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EntityWriteResponseDto) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EntityWriteResponseDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityWriteResponseDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EntityWriteResponseDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EntityWriteResponseDto) SetName(v string) {
	o.Name = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *EntityWriteResponseDto) GetScope() map[string]string {
	if o == nil || IsNil(o.Scope) {
		var ret map[string]string
		return ret
	}
	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityWriteResponseDto) GetScopeOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Scope) {
		return map[string]string{}, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *EntityWriteResponseDto) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given map[string]string and assigns it to the Scope field.
func (o *EntityWriteResponseDto) SetScope(v map[string]string) {
	o.Scope = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *EntityWriteResponseDto) GetProperties() map[string]interface{} {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityWriteResponseDto) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *EntityWriteResponseDto) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]interface{} and assigns it to the Properties field.
func (o *EntityWriteResponseDto) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

func (o EntityWriteResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityWriteResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EntityWriteResponseDto) UnmarshalJSON(data []byte) (err error) {
	varEntityWriteResponseDto := _EntityWriteResponseDto{}

	err = json.Unmarshal(data, &varEntityWriteResponseDto)

	if err != nil {
		return err
	}

	*o = EntityWriteResponseDto(varEntityWriteResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "properties")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntityWriteResponseDto struct {
	value *EntityWriteResponseDto
	isSet bool
}

func (v NullableEntityWriteResponseDto) Get() *EntityWriteResponseDto {
	return v.value
}

func (v *NullableEntityWriteResponseDto) Set(val *EntityWriteResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityWriteResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityWriteResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityWriteResponseDto(val *EntityWriteResponseDto) *NullableEntityWriteResponseDto {
	return &NullableEntityWriteResponseDto{value: val, isSet: true}
}

func (v NullableEntityWriteResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityWriteResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
