/*
Asserts, Inc

Asserts Public API

API version: 2.53.4
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kgwrite

import (
	"encoding/json"
)

// checks if the GraphWriteRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphWriteRequestDto{}

// GraphWriteRequestDto Batch of entities and relationships to upsert atomically. At least one of `entities` or `relationships` must be non-empty; an empty request is a 422.
type GraphWriteRequestDto struct {
	Entities             []EntityWriteRequestDto       `json:"entities,omitempty"`
	Relationships        []RelationshipWriteRequestDto `json:"relationships,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GraphWriteRequestDto GraphWriteRequestDto

// NewGraphWriteRequestDto instantiates a new GraphWriteRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphWriteRequestDto() *GraphWriteRequestDto {
	this := GraphWriteRequestDto{}
	return &this
}

// NewGraphWriteRequestDtoWithDefaults instantiates a new GraphWriteRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphWriteRequestDtoWithDefaults() *GraphWriteRequestDto {
	this := GraphWriteRequestDto{}
	return &this
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *GraphWriteRequestDto) GetEntities() []EntityWriteRequestDto {
	if o == nil || IsNil(o.Entities) {
		var ret []EntityWriteRequestDto
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphWriteRequestDto) GetEntitiesOk() ([]EntityWriteRequestDto, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *GraphWriteRequestDto) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []EntityWriteRequestDto and assigns it to the Entities field.
func (o *GraphWriteRequestDto) SetEntities(v []EntityWriteRequestDto) {
	o.Entities = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *GraphWriteRequestDto) GetRelationships() []RelationshipWriteRequestDto {
	if o == nil || IsNil(o.Relationships) {
		var ret []RelationshipWriteRequestDto
		return ret
	}
	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphWriteRequestDto) GetRelationshipsOk() ([]RelationshipWriteRequestDto, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *GraphWriteRequestDto) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given []RelationshipWriteRequestDto and assigns it to the Relationships field.
func (o *GraphWriteRequestDto) SetRelationships(v []RelationshipWriteRequestDto) {
	o.Relationships = v
}

func (o GraphWriteRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphWriteRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entities) {
		toSerialize["entities"] = o.Entities
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GraphWriteRequestDto) UnmarshalJSON(data []byte) (err error) {
	varGraphWriteRequestDto := _GraphWriteRequestDto{}

	err = json.Unmarshal(data, &varGraphWriteRequestDto)

	if err != nil {
		return err
	}

	*o = GraphWriteRequestDto(varGraphWriteRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "entities")
		delete(additionalProperties, "relationships")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGraphWriteRequestDto struct {
	value *GraphWriteRequestDto
	isSet bool
}

func (v NullableGraphWriteRequestDto) Get() *GraphWriteRequestDto {
	return v.value
}

func (v *NullableGraphWriteRequestDto) Set(val *GraphWriteRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphWriteRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphWriteRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphWriteRequestDto(val *GraphWriteRequestDto) *NullableGraphWriteRequestDto {
	return &NullableGraphWriteRequestDto{value: val, isSet: true}
}

func (v NullableGraphWriteRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphWriteRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
